import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { parseEligibility, validateProposedBps, buildParameterSpec, submitParameter, parameterSubmissionError, PARAMETER_OPERATION, TOKEN_2022_PROGRAM } from './cloud/parameter-model.js';
globalThis.document={documentElement:{dataset:{base:'/p/proj_fixture',project:'proj_fixture',cloud:'1',mode:'overview'}}};
globalThis.localStorage={getItem:()=>null,setItem(){}};
let source=readFileSync(new URL('./cloud/parameter.js',import.meta.url),'utf8');
for(const name of ['env','ui'])source=source.replace(`'./${name}.js'`,JSON.stringify(new URL(`./dashboard/${name}.js`,import.meta.url).href));
source=source.replace("'/assets/capabilities.js'",JSON.stringify(new URL('./src/capabilities.js',import.meta.url).href)).replace("'./parameter-model.js'",JSON.stringify(new URL('./cloud/parameter-model.js',import.meta.url).href));
const {formHTML,previewHTML,attachForm,withParameterPolling}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const {parameterResult}=await import('./dashboard/analytical.js');
const q=JSON.parse(readFileSync(new URL('../docs/examples/protocol-parameter-change-qualification.json',import.meta.url)));
const facts={schema_version:1,eligible:true,project_id:'proj_fixture',run_id:'run_parent',operation:PARAMETER_OPERATION,program_id:TOKEN_2022_PROGRAM,mint:q.change.target.config_account,current_basis_points:50,schedule_epoch:'1032',captured_epoch:'1037',maximum_fee_raw:'18446744073709551615',mint_data_sha256:q.change.operation.expected_current.account_data_sha256,capture_sha256:q.observed_capture_sha256,token_2022_elf_sha256:q.programs[0].elf_sha256,transfer:{source:'retained-source',destination:'retained-destination',amount_raw:'10000',decimals:9}};
const e=parseEligibility(facts,'proj_fixture','run_parent');
const capability={kind:'protocol_parameter_change',status:'ready',supported:true,can_submit:true,missing:[]};
for(const value of ['0','10000','200','50'])assert.equal(validateProposedBps(value),null,value);
for(const value of ['',' ','-1','10001','0.5','1e2','Infinity','NaN'])assert.ok(validateProposedBps(value),value);
assert.throws(()=>parseEligibility(facts,'other','run_parent'));
assert.throws(()=>parseEligibility({...facts,schedule_epoch:1032},'proj_fixture','run_parent'));
assert.throws(()=>parseEligibility({...facts,operation:'another_parameter'},'proj_fixture','run_parent'));
assert.throws(()=>{e.maximum_fee_raw='10';},TypeError);
assert.throws(()=>{e.transfer.source='injected';},TypeError);
const spec=buildParameterSpec(e,'200');
assert.deepEqual(spec,{schema_version:1,change:{kind:'protocol_parameter_change',target:{program_id:TOKEN_2022_PROGRAM,config_account:e.mint},operation:{kind:PARAMETER_OPERATION,expected_current:{account_data_sha256:e.mint_data_sha256,basis_points:50,schedule_epoch:'1032',maximum_fee_raw:'18446744073709551615'},proposed_basis_points:200}}});
assert.equal(Object.hasOwn(spec,'activation'),false);
const html=formHTML(e,capability);
assert.equal((html.match(/<input/g)??[]).length,1);
assert.match(html,/name="proposed_basis_points"/);
for(const field of ['mint','schedule_epoch','maximum_fee_raw','source','destination','account_data_sha256'])assert.doesNotMatch(html,new RegExp(`<input[^>]*name="${field}"`));
const preview=previewHTML(e,'200');
for(const text of ['50 bps → 200 bps','Ready to submit for analysis','Exact ChangeSpec','same retained TransferChecked','18446744073709551615','1032','1,037','retained-source','retained-destination'])assert.ok(preview.includes(text),text);
assert.doesNotMatch(preview,/9950|9800|9,950|9,800|recipient gets|approved|deployable/);
assert.doesNotMatch(preview,/<input|activation/);
assert.match(formHTML({eligible:false,reason_code:'schedule_not_active',reason:'Newer schedule is pending.'},capability),/schedule_not_active/);
assert.doesNotMatch(formHTML({eligible:false,reason:'Pending.'},capability),/<form/);
let sent,navigated;
await submitParameter({eligibility:e,value:'200',requestKey:'key',call:async(path,options)=>{sent={path,body:JSON.parse(options.body)};return {run_id:'run_child'};},navigate:url=>{navigated=url;}});
assert.equal(sent.path,'/v1/projects/proj_fixture/runs/run_parent/parameter-changes');
assert.deepEqual(sent.body,{request_key:'key',change_spec:spec});
assert.equal(navigated,'/p/proj_fixture/runs/run_child');
assert.match(parameterSubmissionError({body:{status:'current_state_mismatch'},message:'Mismatch'}),/evidence/);
assert.equal(parameterSubmissionError(new Error('Server validation rejected the declaration.')),'Server validation rejected the declaration.');
// DOM edits can only supply the rate. No editable/hidden duplicate is read.
const handlers={},previewNode={innerHTML:''},errorNode={textContent:''},submit={disabled:true},input={value:'200',disabled:false};
const form={elements:{proposed_basis_points:input,mint:{value:'injected'},schedule_epoch:{value:'9999'},maximum_fee_raw:{value:'1'},account_data_sha256:{value:'injected'}},querySelector:selector=>({'[data-parameter-preview]':previewNode,'[data-parameter-error]':errorNode,'[data-parameter-submit]':submit,'[data-parameter-preview-button]':{addEventListener:(_,fn)=>{handlers.preview=fn;}}})[selector],addEventListener:(event,fn)=>{handlers[event]=fn;}};
let attempts=0,controllerSent;
attachForm({querySelector:()=>form},e,capability,{key:()=> 'retained-key',navigate:()=>{},call:async(path,options)=>{controllerSent=JSON.parse(options.body);attempts++;throw new Error(attempts===1?'Server validation rejected the declaration.':'current_state_mismatch');}});
handlers.preview();assert.equal(submit.disabled,false);
document.documentElement.dataset.mode='technical';assert.equal(input.value,'200');assert.ok(previewNode.innerHTML.includes('Exact ChangeSpec'));
await handlers.submit({preventDefault(){}});
assert.equal(input.value,'200');assert.equal(input.disabled,false);assert.equal(submit.disabled,false);assert.match(errorNode.textContent,/Server validation/);
assert.deepEqual(controllerSent.change_spec,spec);
await handlers.submit({preventDefault(){}});assert.match(errorNode.textContent,/current_state_mismatch/);assert.equal(input.value,'200');
input.value='201';handlers.input();assert.equal(submit.disabled,true);assert.equal(previewNode.innerHTML,'');
await handlers.submit({preventDefault(){}});assert.match(errorNode.textContent,/Preview/);
input.value='';handlers.preview();assert.equal(submit.disabled,true);assert.match(errorNode.textContent,/Enter/);
const side=s=>({execution:{success:s.success},reconciliation:{reconciled:s.reconciled,input_debited_raw:s.source_debit_raw,output_received_raw:s.recipient_credit_raw,token_accounts:[{}, {withheld_fee_change_raw:s.destination_withheld_increment_raw}]}});
const report={kind:'protocol_parameter_change',status:q.status,execution_performed:true,change:q.change,proposed_declaration:q.declaration,observed_current_state:{mint_sha256:e.mint_data_sha256},baseline:side(q.sides.baseline),proposed:side(q.sides.proposed),shared_execution:{programs:q.programs},findings:q.findings,limitations:q.limits};
const consequence=parameterResult(report);
for(const text of ['50 bps → 200 bps','9,950 → 9,800','50 → 200','Program bytes unchanged','ChangeSpec ID'])assert.ok(consequence.includes(text),text);
const cap=structuredClone(report);cap.status='no_observed_consequence';
for(const k of ['baseline','proposed']){cap[k].reconciliation.output_received_raw='9990';cap[k].reconciliation.token_accounts[1].withheld_fee_change_raw='10';}
cap.findings=[];
assert.match(parameterResult(cap),/No observed consequence for this transfer/);
assert.match(parameterResult(cap),/did not change the measured result of this retained transfer/);
for(const status of ['current_state_mismatch','schedule_not_active','mutation_unsupported','downstream_action_unsupported','execution_unavailable','reconciliation_failed','execution_rejected']) {
 const r=structuredClone(report);r.status=status;
 if(['current_state_mismatch','schedule_not_active','mutation_unsupported','downstream_action_unsupported','execution_unavailable'].includes(status)){delete r.baseline;delete r.proposed;delete r.observed_current_state;r.execution_performed=false;}
 if(status==='reconciliation_failed')r.proposed.reconciliation.reconciled=false;
 const result=parameterResult(r);
 assert.doesNotMatch(result,/recipient_tokens_received|destination_withheld_transfer_fee|9,950 → 9,800/);
 if(status==='schedule_not_active')assert.match(result,/No comparison was executed; Clock was not advanced/);
 if(status==='reconciliation_failed')assert.match(result,/No economic findings are established/);
}
const attack=parameterResult({...report,failure:{detail:'<img src=x onerror=alert(1)>'}});assert.doesNotMatch(attack,/<img/);assert.match(attack,/&lt;img/);
assert.equal(withParameterPolling({html:'durable'}, {hosted:{status:'completed'}},()=>{},()=>{}).html,'durable');
console.log('Parameter Change: eligibility binding, one-field form, structural validation, preview, exact submission, error retention and authoritative result wording verified.');
