import {chromium,expect} from '@playwright/test';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve('media/weekly-2026-09-27'),dir=resolve(root,'assets/motion');
await mkdir(dir,{recursive:true});await mkdir(resolve(dir,'raw'),{recursive:true});
const browser=await chromium.launch({executablePath:process.env.EPLYX_CHROME||'/Users/thomasnguyen/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});
const seed=JSON.parse(await readFile('/private/tmp/eplyx-video-cloud-v2/cloud-seed.json'));
const ids=JSON.parse(await readFile('fixtures/dashboard/ids.json'));
const login=await browser.newContext();const lp=await login.newPage();await lp.goto(seed.base+'/login');await lp.getByLabel('Email').fill(seed.email);await lp.getByLabel('Password').fill(seed.password);await lp.locator('button[type=submit]').click();await expect(lp.locator('h1')).toHaveText('Workspaces');const auth=await login.storageState();await login.close();
const retake=process.argv.includes('--retake');
const manifest=retake?JSON.parse(await readFile(resolve(dir,'capture-log.json'))).filter(x=>!['observe','path','candidate','lifecycle'].includes(x.name)):[];let page,context,started,entry;
async function start(name,{cloud=false,latency=180}={}){
 context=await browser.newContext({viewport:{width:1600,height:900},deviceScaleFactor:1,reducedMotion:'no-preference',recordVideo:{dir:resolve(dir,'raw'),size:{width:1600,height:900}},...(cloud?{storageState:auth}:{})});
 await context.route('**/*',async r=>{const url=new URL(r.request().url());if(url.hostname==='fonts.googleapis.com')return r.fulfill({contentType:'text/css',body:"@font-face{font-family:'Manrope';font-style:normal;font-weight:100 900;src:url('http://127.0.0.1:4189/public/fonts/manrope-latin.woff2')}@font-face{font-family:'DM Sans';font-style:normal;font-weight:100 900;src:url('http://127.0.0.1:4189/public/fonts/dm-sans-latin.woff2')}"});return ['127.0.0.1','localhost'].includes(url.hostname)?r.continue():r.abort();});
 await context.addInitScript(()=>{localStorage.setItem('eplyx-detail','overview');
  addEventListener('DOMContentLoaded',()=>{
   const pointer=document.createElement('div');pointer.id='video-pointer';pointer.style.cssText='position:fixed;left:0;top:0;z-index:2147483647;pointer-events:none;width:26px;height:34px;transform:translate(1500px,820px);filter:drop-shadow(0 2px 3px #0009)';pointer.innerHTML='<svg width="26" height="34" viewBox="0 0 26 34"><path fill="white" stroke="#211034" stroke-width="1.5" d="M2 1L2 27L9 20L15 32L20 29L14 17L25 17Z"/></svg>';document.body.append(pointer);
   addEventListener('mousemove',e=>{pointer.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;});
   addEventListener('mousedown',e=>{const ring=document.createElement('div');ring.style.cssText=`position:fixed;left:${e.clientX-15}px;top:${e.clientY-15}px;width:30px;height:30px;border:2px solid #c29bff;border-radius:50%;pointer-events:none;z-index:2147483646`;document.body.append(ring);ring.animate([{transform:'scale(.4)',opacity:1},{transform:'scale(2)',opacity:0}],{duration:550}).finished.then(()=>ring.remove());});
  });
 });
 page=await context.newPage();started=Date.now();entry={name,raw:name+'.webm',viewport:[1600,900],network_latency_ms:latency,reduced_motion:false,events:[],source:cloud?'Real hosted service; synthetic local provider':'Real local frontend; committed fixture data'};
 const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency,downloadThroughput:5*1024*1024,uploadThroughput:3*1024*1024});
 page.setDefaultTimeout(45000);page.on('pageerror',e=>console.log(name+': '+e.message));
}
const pause=ms=>page.waitForTimeout(ms);
function mark(label){const t=(Date.now()-started)/1000;entry.events.push({time:t,label});console.log(entry.name+' '+t.toFixed(2)+' '+label);}
async function go(url){mark('navigation');await page.goto(url,{waitUntil:'domcontentloaded'});}
async function moveTo(loc){await loc.scrollIntoViewIfNeeded();await pause(250);const b=await loc.boundingBox();if(!b)throw Error('Missing target');const x=b.x+b.width/2,y=b.y+b.height/2;const prev=await page.evaluate(()=>{const t=document.querySelector('#video-pointer')?.style.transform;return t?.match(/[\d.]+/g)?.map(Number)||[1500,820];});for(let i=1;i<=15;i++){await page.mouse.move(prev[0]+(x-prev[0])*i/15,prev[1]+(y-prev[1])*i/15);await pause(13);}return {x,y};}
async function click(loc,label){await moveTo(loc);mark(label);await loc.click();await pause(400);}
async function type(loc,value,label){await moveTo(loc);await loc.click();mark(label);await loc.pressSequentially(value,{delay:24});}
async function scroll(selector,label){mark(label);await page.locator(selector).first().evaluate(el=>window.scrollTo({top:el.getBoundingClientRect().top+scrollY-120,behavior:'smooth'}));await pause(1100);}
async function stop(){await pause(900);entry.duration_wall_seconds=(Date.now()-started)/1000;const video=page.video();await page.close();await context.close();await video.saveAs(resolve(dir,entry.raw));manifest.push(entry);await writeFile(resolve(dir,'capture-log.json'),JSON.stringify(manifest,null,2));console.log('Saved '+entry.name);}

if(!retake){
await start('hero',{latency:70});await go('http://127.0.0.1:4189/');await pause(4600);mark('native hero revealed');await page.mouse.move(1300,450,{steps:24});await pause(600);await page.mouse.move(1050,560,{steps:24});await pause(750);mark('scroll to system');await page.mouse.wheel(0,610);await pause(1500);await stop();

await start('dashboard');await go('http://127.0.0.1:4185/');await expect(page.locator('.hero-status h1')).toHaveText('Failed.');mark('dashboard loaded');await pause(800);await click(page.getByRole('link',{name:'Open run #4',exact:true}),'open saved run');await expect(page.locator('main h1')).toHaveText('Failed.');mark('run loaded');await pause(900);await click(page.getByRole('button',{name:'Technical',exact:true}),'reveal exact technical values');await pause(900);await click(page.getByRole('button',{name:'Overview',exact:true}),'return to overview');await stop();

await start('stress');await go('http://127.0.0.1:4185/runs/'+ids.underfunded);await expect(page.locator('main h1')).toHaveText('Failed.');await scroll('#stress','scroll to stress matrix');await pause(900);const row=page.locator('#stress tr').filter({hasText:'At Deadline'}).first();await moveTo(row);mark('deadline defect row');await pause(1400);await scroll('#gate','inspect deployment gate');await pause(1000);await stop();

await start('witness');await go('http://127.0.0.1:4185/counterexamples/'+ids.derived);await expect(page.locator('main')).toContainText('must reject this migration');mark('witness loaded');await pause(1300);const command=page.locator('.command').filter({hasText:'eplyx migration reproduce'});await scroll('.command','show reproduce command');await click(command.getByRole('button',{name:/Copy/}),'copy actual reproduction command');await pause(1200);await stop();

await start('compare');await go('http://127.0.0.1:4185/runs');await expect(page.locator('tbody tr[data-run]')).toHaveCount(4);mark('run history loaded');await click(page.getByLabel('Select run #3 for comparison'),'select reference');await click(page.getByLabel('Select run #4 for comparison'),'select candidate');await click(page.getByRole('button',{name:'Compare selected'}),'compare selected runs');await expect(page.locator('.story')).toBeVisible();mark('comparison loaded');await pause(1800);await stop();

await start('upgrade',{cloud:true});await go(seed.base+'/p/'+seed.upgradeProject+'/runs');await page.locator('tbody tr[data-run]').first().waitFor();await pause(500);await click(page.locator('tbody tr[data-run] a[data-link]').first(),'open completed upgrade');await expect(page.locator('.hosted-upgrade-report')).toBeVisible();mark('upgrade report loaded');await pause(800);await scroll('#change','inspect exact candidate identity');await pause(700);await scroll('#impact','inspect measured upgrade impact');await pause(1400);await stop();
}

await start('observe',{cloud:true,latency:220});await go(seed.base+'/p/'+seed.analysisProject+'/analyse');await expect(page.locator('h1')).toHaveText('Analyse current state.');mark('form loaded');await type(page.getByLabel('Mint address'),seed.mint,'enter public mint');await moveTo(page.getByLabel('Inspection scope'));await page.getByLabel('Inspection scope').selectOption('wallet');await pause(300);await type(page.getByLabel('Public owner address'),seed.owner,'enter public owner');await click(page.getByRole('button',{name:'Observe current state',exact:true}),'submit observation');await expect(page.getByLabel('Focused account')).toHaveValue(seed.source);mark('observation resolved');const observedURL=page.url();await scroll('[data-observation]','reveal observed state');await pause(1800);await stop();

await start('path',{cloud:true,latency:220});await go(observedURL);await expect(page.getByLabel('Focused account')).toHaveValue(seed.source);await scroll('[data-path-form]','focus one transfer path');await page.getByLabel('Amount',{exact:true}).selectOption('Custom');await type(page.getByLabel('Custom amount',{exact:true}),'0.0000001','enter exact transfer amount');await type(page.getByLabel('Recipient token account'),'124XHuTYUNnCf2ABCNcCEdQFpHQ7Y6MnPe9NeouDB1az','enter destination token account');await click(page.getByRole('button',{name:'Run offline path check'}),'queue offline transfer');await scroll('[data-path-result]','follow queued check');await expect(page.locator('[data-path-result]')).toContainText('Recorded result:',{timeout:60000});mark('actual transfer result');await scroll('[data-path-result]','focus final transfer result');await pause(2000);await stop();

await start('candidate',{cloud:true,latency:220});await go(observedURL);await expect(page.getByLabel('Focused account')).toHaveValue(seed.source);await scroll('[data-candidate-form]','candidate terms');await type(page.getByLabel('Replacement mint',{exact:true}),'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v','enter replacement mint');await page.getByRole('combobox',{name:'Candidate amount',exact:true}).selectOption('Custom');await type(page.getByLabel('Candidate custom amount'),'0.0000001','choose candidate amount');await click(page.getByRole('button',{name:'Run candidate check'}),'queue candidate execution');await scroll('[data-candidate-result]','follow immutable candidate job');await expect(page.locator('[data-candidate-result]')).toContainText('Exact checks passed',{timeout:60000});mark('candidate result loaded');await scroll('[data-candidate-result]','focus final candidate result');await pause(2000);await stop();

await start('lifecycle',{cloud:true,latency:220});await go(observedURL);await expect(page.getByLabel('Focused account')).toHaveValue(seed.source);await scroll('[data-preflight-form]','declare lifecycle scenario');await page.getByLabel('Saved candidate plan (optional)').selectOption({index:1});await type(page.getByLabel('Scenario replacement mint (optional)'),'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v','bind successor mint');await page.getByLabel('Proposed effective time').fill('2031-01-01T12:00');await page.getByLabel('Proposed deadline (optional)').fill('2032-01-01T12:00');mark('set effective date and deadline');await pause(650);await click(page.getByRole('button',{name:'Evaluate proposed scenario'}),'queue lifecycle evaluation');await scroll('[data-preflight-result]','follow scenario evaluation');await expect(page.locator('[data-preflight-result]')).toContainText('Prepared',{timeout:60000});mark('separate assurance results loaded');await scroll('[data-preflight-result]','focus all assurance results');await pause(2400);await stop();
await browser.close();
