// Views of saved lifecycle/current outputs. No status is inferred from missing
// fields and no path inherits another path's execution evidence.
import { esc, words, pill, tile, panel, kv, ident, raw, count, when, empty } from './ui.js';
import { BASE } from './env.js';
const NAMES = { protocol_parameter_change:'Token-2022 fee counterfactual', lifecycle_change:'Lifecycle analysis', current_observation:'Current observation', current_path:'Current path check', current_candidate:'Candidate migration', current_preflight:'Proposed scenario', current_stress:'Bounded migration stress', program_upgrade:'Program upgrade' };
const name = run => run.kind==='protocol_parameter_change' && run.change?.operation?.kind==='spl_stake_pool_sol_deposit_fee_v1' ? 'Stake Pool deposit fee simulation' : NAMES[run.kind] ?? 'Analytical record';
export const analyticalCells = run => `<span class="tag">${esc(name(run))}</span>`;
const parameterLabels={semantic_consequence_observed:'Measured change',no_observed_consequence:'Same measured result',current_state_mismatch:'Evidence mismatch',schedule_not_active:'Pending schedule',mutation_unsupported:'Unsupported mutation',downstream_action_unsupported:'Unsupported transfer',execution_rejected:'Execution rejected',execution_unavailable:'Execution unavailable',reconciliation_failed:'Reconciliation failed',config_evidence_missing:'Missing evidence',unsupported_config_field:'Unsupported field',invalid_proposed_value:'Invalid rate',config_execution_rejected:'Configuration rejected',config_execution_unavailable:'Configuration unavailable',post_config_state_mismatch:'Post-configuration mismatch'};
export function analyticalTiles(run) {
 return `<div class="tiles tiles--3${run.kind==='protocol_parameter_change'?' tiles--parameter':''}">${tile({ label:'Analysis', value:esc(name(run)) })}${tile({ label:'Record', value:pill(run.state) })}${tile({ label:run.kind==='protocol_parameter_change'?'Analytical result':'Execution', value:run.kind==='protocol_parameter_change'?esc(parameterLabels[run.status]??words(run.status)):run.kind === 'current_observation' || run.kind === 'lifecycle_change' ? pill('NotTested') : pill(run.status), sub:'Only the recorded scope applies.' })}</div>`;
}
const entries = value => Object.entries(value ?? {}).map(([key, value]) => [words(key), typeof value === 'object' ? `<code>${esc(JSON.stringify(value))}</code>` : esc(words(value))]);
const technicalJSON = value => { const text=JSON.stringify(value,null,2); return text.length<=65536?esc(text):`${esc(text.slice(0,65536))}\n… Preview limited to 64 KiB. Open the complete report artifact for every field.`; };
const limits = values => `<ul class="limits">${(values ?? []).map(v => `<li>${esc(v)}</li>`).join('')}</ul>`;
function lifecycle(report) {
 const impact=report.impact ?? report, summary=impact.summary ?? {};
 const entities=impact.entities ?? [], protocols=impact.protocol_observations ?? [];
 const rows=(items, protocol=false) => `<div class="table-wrap"><table class="table"><thead><tr><th>${protocol?'Protocol observation':'Entity'}</th><th>Before</th><th>After</th><th>Classification</th><th>Execution</th><th class="tech-only">Public raw balance</th></tr></thead><tbody>${items.slice(0,100).map(e => `<tr><td>${ident(e.entity_id ?? e.token_account,'addr')}</td><td>${esc(words(e.pre_lifecycle_status))}</td><td>${esc(words(e.post_lifecycle_status))}</td><td>${esc(words(e.impact_classification))}</td><td>${pill(e.execution_status)}</td><td class="tech-only">${raw(e.balance?.raw)}</td></tr>`).join('')}</tbody></table></div>${items.length>100?`<p>Showing 100 of ${count(items.length)} records. The complete output is in the report.</p>`:''}`;
 return `${panel({ id:'policy',title:'Declared policy',body:`<p>Lifecycle times change the interpretation of this pinned snapshot. They do not capture new chain state or establish an issuer transition.</p>${kv([['Before',esc(when(impact.before?.evaluated_at))],['After',esc(when(impact.after?.evaluated_at))],['Before status',esc(words(impact.before?.lifecycle_status))],['After status',esc(words(impact.after?.lifecycle_status))],['Policy basis',pill('OperatorSupplied')]])}` })}
 ${panel({ id:'consequence',title:'Entity consequences',body:`${kv([['Entities evaluated',count(summary.entities_evaluated)],['Positive public balances',count(summary.positive_balance_entities)],['Changed economic meaning',count(summary.economic_meaning_changed_entities)],['Affected public balance (raw)',raw(summary.phase2_affected_public_raw_exposure),'tech-only']])}${rows(entities)}` })}
 ${panel({ id:'protocols',title:'Protocol observations',body:`<p>These observations refer to the same entities. Their balances are not added to entity totals.</p>${protocols.length?rows(protocols,true):empty('No protocol observations recorded.')}` })}
 ${panel({ id:'limits',title:'Scope and limitations',body:limits([...(report.limitations??[]),...(impact.limitations??[])]) })}`;
}
const parameterStatus = {
 semantic_consequence_observed:'The engine established a reconciled consequence for this exact retained transfer.',
 no_observed_consequence:'This proposed fee change did not change the measured result of this retained transfer.',
 current_state_mismatch:'Current-state mismatch: the declaration does not match the retained mint evidence. No transfer comparison was executed. A newer state requires a new retained transfer run.',
 schedule_not_active:'The newer fee schedule is pending at the retained Clock epoch. No comparison was executed; Clock was not advanced.',
 mutation_unsupported:'Isolated preservation of the supported mint field could not be established. No transfer comparison was executed.',
 downstream_action_unsupported:'The retained transfer is outside the supported account or extension contract. No transfer comparison was executed.',
 execution_rejected:'The supported transfer execution was rejected. Inspect the recorded error and rollback evidence.',
 execution_unavailable:'The execution infrastructure could not produce the paired comparison.',
 reconciliation_failed:'Execution evidence did not reconcile. No economic findings are established.',
 config_evidence_missing:'Required retained capture evidence is missing or inconsistent. No transfer comparison was executed.',
 unsupported_config_field:'This retained configuration does not support the one active newer transfer-fee field.',
 invalid_proposed_value:'The proposed fee must be an integer from 0 to 10000 basis points.',
};
function stakePoolParameterResult(report) {
 const operation=report.change?.operation??{},current=operation.expected_current??{},proposed=operation.proposed_fee??{};
 const config=report.simulated_config_instruction,observed=report.observed_current_state??{};
 const ratio=f=>`${esc(f.numerator??'Not recorded')}/${esc(f.denominator??'Not recorded')}`;
 const program=observed.programs?.find(p=>p.program_id===report.change?.target?.program_id);
 const rows=[['Baseline',report.baseline],['Proposed',report.proposed]].map(([name,side])=>{
  const r=side?.reconciliation?.reconciled===true?side.reconciliation:{};
  return `<tr><td>${esc(name)}</td><td>${esc(side?side.execution?.success?'Succeeded':side.execution?.error??'Rejected':'Not executed')}</td><td>${raw(r.recipient_account_credit_raw)}</td><td>${raw(r.manager_fee_account_credit_raw)}</td><td>${r.referral_account_credit_raw==null?'Aliased; split not independently measured':raw(r.referral_account_credit_raw)}</td><td>${raw(r.mint_supply_delta_raw)}</td><td>${raw(r.pool_token_supply_delta_raw)}</td><td>${raw(r.reserve_lamport_delta)}</td></tr>`;
 }).join('');
 return `${panel({id:'observation',title:'Historical Stake Pool deposit fee',body:`${kv([['Exact fee',`${ratio(current)} → ${ratio(proposed)}`],['Result',esc(words(report.status))],['Historical record',esc(observed.record_id)],['Slot',raw(observed.slot)],['Pool',ident(report.change?.target?.config_account,'addr')],['Program unchanged',ident(program?.elf_sha256)],['Observed referral percent',raw(current.sol_referral_fee_percent)],['Pool last-update epoch',raw(current.last_update_epoch)],['Retained Clock epoch',raw(config?.clock?.epoch ?? report.retained_input?.record?.clock?.epoch)],['Manager signer','Assumed for the isolated configuration simulation'],['Configuration execution',esc(config?config.execution?.success?'Succeeded':config.execution?.error??'Rejected':'Not executed')],['Separate configuration fee (lamports)',raw(config?.execution?.transaction_fee_lamports)]])}<p>Observed historical state → declared proposal → simulated SetFee → verified instruction-produced pool state → independent DepositSol results.</p><p>No manager key possession, governance approval or on-chain update is established. Both user-action executions use the same historical program bytes.</p>${report.failure?.detail?`<p>${esc(report.failure.detail)}</p>`:''}<div class="tech-only">${kv([['ChangeSpec ID',ident(report.change?.change_spec_id)],['Record SHA-256',ident(observed.record_sha256)],['Pool data SHA-256',ident(current.account_data_sha256)],['Retained bundle SHA-256',ident(observed.source_bundle_sha256)]])}</div>`})}${panel({id:'paths',title:'DepositSol execution and reconciliation',body:`${report.status==='no_observed_consequence'?'<p>No observed consequence for this retained deposit.</p>':''}${[report.baseline,report.proposed].some(side=>side?.reconciliation_error)?`<p>${esc([report.baseline?.reconciliation_error,report.proposed?.reconciliation_error].filter(Boolean).join('; '))}</p>`:''}<div class="table-wrap"><table class="table"><thead><tr><th>Side</th><th>Execution</th><th>Recipient credit</th><th>Manager fee credit</th><th>Referral credit</th><th>Mint supply delta</th><th>Pool supply delta</th><th>Reserve lamports</th></tr></thead><tbody>${rows}</tbody></table></div><p>All token quantities are exact raw pool-token units. Aliased accounts are counted once. Configuration fees are excluded from DepositSol economics.</p><details class="tech-only"><summary>Recorded findings</summary><pre>${esc(JSON.stringify(report.findings??[],null,2))}</pre></details>`})}${panel({id:'limits',title:'Scope and limitations',body:limits(report.limitations)})}`;
}
export function parameterResult(report) {
 if(report.change?.operation?.kind==='spl_stake_pool_sol_deposit_fee_v1')return stakePoolParameterResult(report);
 const declared=report.change?.operation??{}, expected=declared.expected_current??{}, proposal=report.proposed_declaration??{};
 const current=proposal.current_bps??expected.basis_points, proposed=proposal.proposed_bps??declared.proposed_basis_points;
 const measured=report.baseline?.execution?.success===true && report.proposed?.execution?.success===true && report.baseline?.reconciliation?.reconciled===true && report.proposed?.reconciliation?.reconciled===true && ['semantic_consequence_observed','no_observed_consequence'].includes(report.status);
 const rows=[['Baseline',report.baseline],['Proposed',report.proposed]].map(([name,side])=>{
  const reconciled=side?.reconciliation?.reconciled===true && report.status!=='reconciliation_failed';
  return `<tr><td>${esc(name)}</td><td>${side?esc(side.execution?.success?'Succeeded':side.execution?.error??'Rejected'):'Not executed'}</td><td>${raw(reconciled?side.reconciliation.input_debited_raw:null)}</td><td>${raw(reconciled?side.reconciliation.output_received_raw:null)}</td><td>${raw(reconciled?side.reconciliation.token_accounts?.[1]?.withheld_fee_change_raw:null)}</td><td>${esc(reconciled?'Reconciled':'Not established')}</td></tr>`;
 }).join('');
 const changes=measured?kv([['Recipient public credit',`${raw(report.baseline.reconciliation.output_received_raw)} → ${raw(report.proposed.reconciliation.output_received_raw)} raw`],['Destination withheld fee',`${raw(report.baseline.reconciliation.token_accounts?.[1]?.withheld_fee_change_raw)} → ${raw(report.proposed.reconciliation.token_accounts?.[1]?.withheld_fee_change_raw)} raw`]]):'';
 const program=report.shared_execution?.programs?.find(p=>p.program_id===report.change?.target?.program_id);
 return `${panel({id:'observation',title:'Active-state fee counterfactual',body:`${kv([['Configuration',`${raw(current)} bps → ${raw(proposed)} bps`],['Result',esc(words(report.status))],[report.observed_current_state?'Current fee':'Expected current fee',`${raw(current)} bps`],['Proposed fee',`${raw(proposed)} bps`],['Mint',ident(report.change?.target?.config_account,'addr')],['Captured epoch',raw(proposal.captured_epoch??report.retained_input?.fixture?.clock?.epoch)],['Schedule epoch',raw(proposal.newer_schedule_epoch??expected.schedule_epoch)],['Maximum fee (raw)',raw(proposal.maximum_fee_raw??expected.maximum_fee_raw)]])}<p>${esc(parameterStatus[report.status]??'Inspect the exact recorded analytical status.')}</p>${report.failure?.detail?`<p>${esc(report.failure.detail)}</p>`:''}<p>${report.execution_performed&&program?'Program code unchanged. Program bytes unchanged.':'The comparison contract fixes the same retained program code and Clock.'}</p><div class="tech-only">${kv([['ChangeSpec ID',ident(report.change?.change_spec_id)],['Operation',esc(declared.kind)],['Mint data SHA-256 (expected)',ident(expected.account_data_sha256)],['Capture SHA-256',ident(report.observed_capture_sha256)],['Baseline Token-2022 ELF SHA-256',ident(program?.elf_sha256)],['Proposed Token-2022 ELF SHA-256',ident(program?.elf_sha256)]])}</div>`})}${panel({id:'paths',title:measured?'Observed consequence':'Retained execution and reconciliation',body:`${report.status==='no_observed_consequence'?'<p>No observed consequence for this transfer.</p>':''}${changes}<div class="table-wrap"><table class="table"><thead><tr><th>Side</th><th>Execution</th><th>Source debit</th><th>Recipient credit</th><th>Withheld increment</th><th>Evidence</th></tr></thead><tbody>${rows}</tbody></table></div><p>All quantities are raw token units. No SetTransferFee instruction, authority possession or on-chain activation is established.</p>${measured?`<details class="tech-only"><summary>Recorded findings</summary><pre>${esc(JSON.stringify(report.findings??[],null,2))}</pre></details>`:''}`})}${panel({id:'limits',title:'Scope and limitations',body:`<p>One exact retained TransferChecked under captured current-state evidence. Other holders and transfer amounts are not covered.</p>${limits(report.limitations)}`})}`;
}
function current(report) {
 if(report.kind==='protocol_parameter_change') return parameterResult(report);
 if(report.kind==='current-stress'){const r=report.report??{},c=r.coverage??{};return `${panel({id:'observation',title:'Frozen bounded sample',body:`<p>Cases were selected before their outcomes and rebound to each exact coherent final state. Selection is not a statistical sample.</p>${kv([['Selected',count(c.exact_accounts_selected)],['Executed',count(c.exact_accounts_executed)],['Proven',count(c.exact_accounts_proven)],['Population rollout',pill(c.population_rollout_readiness)],['Official transition',pill(r.official_transition)]])}`})}${panel({id:'paths',title:'Exact case results',body:`<div class="table-wrap"><table class="table"><thead><tr><th>Account</th><th>Selected amount</th><th>Final amount</th><th>Result</th><th>Scope</th></tr></thead><tbody>${(r.results??[]).map(c=>`<tr><td>${ident(c.token_account,'addr')}</td><td>${raw(c.selected_amount_raw)}</td><td>${raw(c.final_amount_raw)}</td><td>${pill(c.status)}</td><td>${esc(c.reason??words(c.classification))}</td></tr>`).join('')}</tbody></table></div><p>Amounts are raw integers. Outcomes are independent; they do not establish shared reserve capacity or authority possession.</p>`})}${panel({id:'limits',title:'Scope and limitations',body:limits([...(report.limitations??[]),...(r.limitations??[])])})}`;}

 if(report.kind==='current-candidate')return `${panel({id:'observation',title:'Candidate migration',body:`${kv([['Result',pill(report.status)],['Exact input (raw)',raw(report.amount_raw)],['Replacement mint',ident(report.replacement_mint,'addr')],['Local execution',report.execution_performed?'Performed':'Not performed'],['Reconciliation',report.execution?.reconciled?'Exact checks passed':'No reconciled success'],['Official transition',pill(report.official_transition)],['Signing possession','Cannot be judged']])}<p>${esc(report.reason??'Only this candidate, account and amount are covered.')}</p>`})}${panel({id:'paths',title:'Declared terms and observed state',body:`<p>The reserve is a proposed overlay. No issuer funding or official mechanism is established.</p>${kv([['Observed balance (raw)',raw(report.plan_unit?.source_balance_raw)],['Proposed output (raw)',raw(report.plan_unit?.quote?.output_raw)],['Candidate SHA-256',ident(report.candidate_program_sha256)]])}`})}${panel({id:'limits',title:'Scope and limitations',body:limits(report.limitations)})}`;
 if(report.kind==='current-preflight')return `${panel({id:'observation',title:'User-proposed scenario',body:`<p>Hypothetical policy applied to unchanged captured state. Issuer association is unconfirmed.</p>${kv([['Preparation',esc(words(report.preparation_status))],['Source account',ident(report.entity?.account,'addr')],['Balance (raw)',raw(report.entity?.balance_raw)],['Successor inspection',esc(words(report.successor_verification?.status))],['Candidate plan',pill(report.replacement_conversion?.status)]])}`})}${panel({id:'paths',title:'Separate assurance questions',body:`<div class="table-wrap"><table class="table"><thead><tr><th>Policy time</th><th>Mobility</th><th>Candidate plan</th><th>Full transition</th></tr></thead><tbody>${(report.views??[]).map(v=>`<tr><td>${esc(words(v.id))}</td>${['mobility','candidate_plan','full_transition'].map(g=>`<td>${v.readiness?pill(v.readiness[g]?.status):'Before event; not evaluated'}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>These findings cover the selected entity and exact tested amounts. Population readiness is not assessed.</p>`})}${panel({id:'limits',title:'Scope and limitations',body:limits(report.limitations)})}`;

 const observation=report.kind==='current-inspection', wallet=report.wallet_observation;
 const paths=report.paths ?? (report.path ? [{path:report.path,status:report.status,reason:report.reason}] : []);
 const checks=(report.accounts??[]).flatMap(a=>(a.checks??[]).map(c=>({...c,source:a.source})));
 return `${panel({ id:'observation',title:observation?'Current observation':'Recorded check',body:`${kv([
 ['Kind',esc(words(report.kind ?? 'Declared check'))],['Mint',ident(report.asset?.mint ?? report.mint,'addr')],['Source account',ident(report.source,'addr')],['Public owner',ident(wallet?.public_owner ?? report.owner,'addr')],['Acquisition completed',esc(when(report.acquisition?.completed_at))],['Execution performed',report.execution_performed===true?'Yes, in the local VM':report.execution_performed===false?'No':'Not recorded'],['Signing possession',report.signer_possession_known===true?'Recorded by engine':'Cannot be judged'],['Scope',esc(report.scope ?? 'Only the selected mint and recorded accounts. Refresh starts untested.')],
 ])}${report.inspection?kv(entries(report.inspection)):''}${report.discovery?kv(entries(report.discovery)):''}` })}
 ${panel({ id:'paths',title:'Paths remain separate',body:`<p>Transfer, market exit, withdrawal, redemption and official transition keep separate evidence. A token transfer does not establish a market exit.</p>${paths.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Path</th><th>Recorded status</th><th>Reason</th></tr></thead><tbody>${paths.map(p=>`<tr><td>${esc(words(p.path))}</td><td>${pill(p.status)}</td><td>${esc(p.reason??'')}</td></tr>`).join('')}</tbody></table></div>`:empty('No path result recorded.')}${checks.length?`<h3>Available checks.</h3>${checks.map(c=>`<p>${ident(c.source,'addr')} · ${esc(words(c.path))} · ${pill(c.status)} ${esc(c.reason??'')}</p>`).join('')}<p>Availability is not execution proof.</p>`:''}` })}
 ${wallet?panel({ id:'wallet',title:'Owner and selected mint',body:`<p>A public owner address does not prove control of its keys.</p>${kv(entries({status:wallet.status,...wallet.summary}))}<div class="table-wrap"><table class="table"><thead><tr><th>Token account</th><th>Public balance</th><th>State</th></tr></thead><tbody>${(wallet.token_accounts??[]).slice(0,100).map(a=>`<tr><td>${ident(a.address,'addr')}</td><td>${raw(a.state?.raw_balance ?? a.raw_balance ?? a.amount_raw)}</td><td>${esc(words(a.state?.account_state ?? (typeof a.state==='string'?a.state:a.status)))}</td></tr>`).join('')}</tbody></table></div>` }):''}
 ${panel({id:'limits',title:'Scope and limitations',body:limits(report.limitations ?? [report.scope ?? 'No other account, amount, recipient, position, range, bank or path inherits this result.'])})}`;
}
export function analyticalDetail(detail,{evidenceBlock}={}) {
 if(detail.kind==='program_upgrade')return {title:'Program upgrade',html:`<div class="page-head"><h1>Program upgrade.</h1><p class="muted">${esc(detail.id)}</p></div>${panel({title:'Recorded run',body:`${kv([['Run status',pill(detail.status)],['Result',pill(detail.state)]])}<p>The report separates historical execution fidelity, economic impact, declared changes and the CI gate.</p><a class="button" href="${BASE}/runs/${esc(detail.id)}" data-link>Open program-upgrade report</a>`})}`};
 const report=detail.analysis?.report ?? {};
 const content=detail.state!=='Complete'?empty(detail.problems?.join('; ') || (detail.state==='ExecutionError' ? detail.hosted?.detail || 'The worker failed; no analytical result is available.' : 'This run has not finished.')):detail.kind==='lifecycle_change'?lifecycle(report):current(report);
 return {title:name(detail),crumbs:[['Runs','/runs'],[`#${detail.number??'?'}`]],html:`<div class="page-head"><div><span class="eyebrow">Run #${esc(detail.number??'?')}</span><h1>${esc(name(detail))}.</h1><p class="muted">${esc(detail.claim_basis??'Saved engine output.')}</p></div></div>${analyticalTiles(detail)}<nav class="subnav" aria-label="Run sections"><a href="#${detail.kind==='lifecycle_change'?'policy':'observation'}">Input</a><a href="#${detail.kind==='lifecycle_change'?'consequence':'paths'}">Results</a><a href="#limits">Limitations</a><a href="#evidence">Evidence</a></nav>${content}${panel({id:'evidence',title:'Evidence',body:evidenceBlock?evidenceBlock(detail):kv(entries(detail.evidence?.hashes))})}${panel({cls:'tech-only',title:'Recorded JSON',body:`<pre>${technicalJSON(report)}</pre>`})}`};
}
export function analyticalOverview(detail,project,helpers) {
 const view=analyticalDetail(detail,helpers);
 return {title:'Overview',html:`${view.html}${panel({title:'Recent runs',body:helpers.runsTable(project.recent_runs??[])})}`};
}
export function analyticalCompare(c,{fieldTable}) {
 return {title:'Compare',html:`<div class="page-head"><h1>Compare analytical records.</h1><p>${esc(c.causality)}</p></div><nav class="subnav"><a href="${BASE}/runs/${esc(c.left.id)}" data-link>Run A</a><a href="${BASE}/runs/${esc(c.right.id)}" data-link>Run B</a></nav>${panel({title:'Input differences',body:fieldTable(c.inputs)})}${panel({title:'Recorded result differences',body:fieldTable(c.results)})}`};
}
