import {test,expect} from '@playwright/test';
import {readFileSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
const scratch=process.env.EPLYX_CLOUD_BROWSER_DIR||join(tmpdir(),'eplyx-cloud-browser-results');
const seed=()=>JSON.parse(readFileSync(join(scratch,'cloud-seed.json')));
test.beforeAll(async()=>{for(let n=0;n<300&&!existsSync(join(scratch,'cloud-seed.json'));n++)await new Promise(r=>setTimeout(r,100));expect(existsSync(join(scratch,'cloud-seed.json'))).toBeTruthy();});
test.beforeEach(async({page})=>{page.on('pageerror',e=>{throw e;});await page.goto('/login');await page.getByLabel('Email').fill(seed().email);await page.getByLabel('Password').fill(seed().password);await page.locator('button[type=submit]').click();await expect(page.locator('h1')).toHaveText('Workspaces');await page.goto(`/p/${seed().analysisProject}/analyse`);await expect(page.locator('h1')).toHaveText('Analyse current state.');});
test('catalogue names remain assertions and arbitrary mint observations survive reload',async({page})=>{
 await expect(page.getByLabel('Asset').locator('option')).toHaveCount(10);await expect(page.locator('main')).toContainText('Names are source assertions');
 await page.getByLabel('Mint address').fill(seed().mint);await page.getByRole('button',{name:'Observe current state',exact:true}).click();await expect(page.locator('[data-observation]')).toContainText('Custom token address; issuer identity unconfirmed');await expect(page.locator('[data-observation] tbody tr')).toHaveCount(5);await expect(page.locator('[data-observation]')).not.toContainText('Verified in the local VM');
 const first=page.url();await page.reload();await expect(page.locator('[data-observation]')).toContainText(seed().mint);await page.getByLabel('Mint address').fill(seed().mint);await page.getByRole('button',{name:'Observe current state',exact:true}).click();await expect(page).not.toHaveURL(first);await expect(page.locator('[data-observation]')).not.toContainText('Verified in the local VM');
});
test('focused Transfer check reports local execution and refresh returns to untested',async({page})=>{
 await page.getByLabel('Mint address').fill(seed().mint);await page.getByLabel('Inspection scope').selectOption('wallet');await page.getByLabel('Public owner address').fill(seed().owner);await page.getByRole('button',{name:'Observe current state',exact:true}).click();await expect(page.getByLabel('Focused account')).toHaveValue(seed().source);
 await page.getByLabel('Amount',{exact:true}).selectOption('Custom');await page.getByLabel('Custom amount',{exact:true}).fill('0.0000001');await page.getByLabel('Recipient token account').fill('124XHuTYUNnCf2ABCNcCEdQFpHQ7Y6MnPe9NeouDB1az');await page.getByRole('button',{name:'Run offline path check'}).click();await expect(page.locator('[data-path-result]')).toContainText('Recorded result:',{timeout:30000});await expect(page.locator('[data-path-result]')).toContainText('Performed');await expect(page.locator('[data-path-result]')).toContainText('Cannot be judged');
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:join(scratch,'current-transfer.png'),fullPage:true});await page.getByRole('button',{name:'Refresh current observation'}).click();await expect(page.locator('[data-path-result]')).toBeEmpty();await expect(page.locator('[data-observation]')).not.toContainText('Recorded result:');
});
test('current analysis remains within a narrow viewport and exposes no provider or program input',async({page})=>{await page.setViewportSize({width:390,height:844});await expect(page.locator('input[name*=rpc],input[name*=program],input[type=file]')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:join(scratch,'current-mobile.png'),fullPage:true});});

test('candidate proposal and hypothetical lifecycle keep independent assurance questions',async({page})=>{test.setTimeout(90000);
 await page.getByLabel('Mint address').fill(seed().mint);await page.getByLabel('Inspection scope').selectOption('wallet');await page.getByLabel('Public owner address').fill(seed().owner);await page.getByRole('button',{name:'Observe current state',exact:true}).click();await expect(page.getByLabel('Focused account')).toHaveValue(seed().source);
 await page.getByLabel('Replacement mint',{exact:true}).fill('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v');await page.getByRole('combobox',{name:'Candidate amount',exact:true}).selectOption('Custom');await page.getByLabel('Candidate custom amount').fill('0.0000001');await page.getByRole('button',{name:'Run candidate check'}).click();await expect(page.locator('[data-candidate-result]')).toContainText('Exact checks passed',{timeout:30000});await expect(page.locator('[data-candidate-result]')).toContainText('Not evaluated');
 await page.getByLabel('Saved candidate plan (optional)').selectOption({index:1});await page.getByLabel('Scenario replacement mint (optional)').fill('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v');await page.getByLabel('Proposed effective time').fill('2031-01-01T12:00');await page.getByLabel('Proposed deadline (optional)').fill('2032-01-01T12:00');await page.getByRole('button',{name:'Evaluate proposed scenario'}).click();await expect(page.locator('[data-preflight-result]')).toContainText('Prepared',{timeout:30000});await expect(page.locator('[data-preflight-result]')).toContainText('Ready');await expect(page.locator('[data-preflight-result]')).toContainText('Incomplete');await expect(page.locator('[data-preflight-result]')).toContainText('Before event; not evaluated');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:join(scratch,'current-proposal.png'),fullPage:true});
 await page.getByLabel('Candidate for stress').selectOption({index:1});await page.getByRole('button',{name:'Run bounded stress'}).click();await expect(page.locator('[data-stress-result]')).toContainText('Bounded stress completed.',{timeout:30000});await expect(page.locator('[data-stress-result]')).toContainText('Incomplete');
 const completedRun=await page.locator('[data-preflight-result]').getByRole('link',{name:'View complete run'}).getAttribute('href');
 await page.getByLabel('Focused account').selectOption({index:1});for(const selector of ['[data-candidate-result]','[data-preflight-result]','[data-stress-result]'])await expect(page.locator(selector)).toBeEmpty();await page.goto(completedRun);await expect(page.locator('main')).toContainText('Separate assurance questions');await expect(page.locator('main')).toContainText('Population readiness is not assessed');
});

test('bounded market exit keeps minimum output and its separate execution result',async({page})=>{
 await page.getByLabel('Mint address').fill(seed().mint);await page.getByLabel('Inspection scope').selectOption('wallet');await page.getByLabel('Public owner address').fill(seed().owner);await page.getByRole('button',{name:'Observe current state',exact:true}).click();await expect(page.getByLabel('Focused account')).toHaveValue(seed().source);
 const form=page.locator('[data-path-form]');await form.locator('[name=path]').selectOption('SecondaryMarketExit');await form.locator('[name=amount_mode]').selectOption('Custom');await form.locator('[name=amount_decimal]').fill('0.00001');await form.locator('[name=output_mint]').fill('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v');await form.locator('[name=minimum_output_decimal]').fill('0.000001');await page.getByRole('button',{name:'Run offline path check'}).click();await expect(page.locator('[data-path-result]')).toContainText('Recorded result:',{timeout:30000});await expect(page.locator('[data-path-result]')).toContainText('Performed');await expect(page.locator('[data-path-result]')).toContainText('Verified in the local VM');
});

test('catalogue selection restores a custom draft and failed submissions never present old evidence',async({page})=>{
 await page.getByLabel('Mint address').fill(seed().mint);await page.getByRole('combobox',{name:'Asset',exact:true}).selectOption({index:1});await page.getByRole('combobox',{name:'Asset',exact:true}).selectOption('');await expect(page.getByLabel('Mint address')).toHaveValue(seed().mint);
 await page.getByRole('button',{name:'Observe current state',exact:true}).click();await expect(page.locator('[data-observation]')).toContainText(seed().mint);await page.getByLabel('Mint address').fill('invalid');await page.getByRole('button',{name:'Refresh current observation'}).click();await expect(page.locator('[data-analysis-status]')).toContainText('invalid');await expect(page.locator('[data-observation]')).toBeEmpty();expect(page.url()).not.toContain('observation=');
});


test('wallet precision, zero balance and focus remain scoped public observations',async({page})=>{
 await page.getByLabel('Mint address').fill(seed().mint);await page.getByLabel('Inspection scope').selectOption('wallet');await page.getByLabel('Public owner address').fill(seed().owner);await page.getByRole('button',{name:'Observe current state',exact:true}).click();
 const focus=page.getByLabel('Focused account');await expect(focus.locator('option')).toHaveCount(3);await expect(focus).toContainText('9007199254740993');
 await focus.selectOption({index:1});await expect(page.locator('[data-path-availability]')).toContainText('No positive public balance');await expect(page.getByRole('button',{name:'Run offline path check'})).toBeDisabled();
 await focus.selectOption({index:0});await expect(page.getByRole('button',{name:'Run offline path check'})).toBeEnabled();await expect(page.locator('[data-path-result]')).toBeEmpty();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:join(scratch,'current-wallet-mobile.png'),fullPage:true});
});
