// Local mock over MAIN's hash-verified frozen fixture. Never contacts a provider.
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
function base58(bytes){const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=BigInt('0x'+Buffer.from(bytes).toString('hex')),out='';while(n){out=alphabet[Number(n%58n)]+out;n/=58n;}for(const byte of bytes){if(byte!==0)break;out='1'+out;}return out;}
export async function observationRPC(repo){
 const fixture=JSON.parse(await readFile(join(repo,'fixtures/lifecycle/main-t7/probes/phase7-captures/fixtures/group-0.json'),'utf8'),(_key,value,context)=>typeof value==='number'&&Number.isInteger(value)&&!Number.isSafeInteger(value)?JSON.rawJSON(context.source):value);
 const batch=fixture.evidence[3],raw=new Map(batch.params[0].map((a,i)=>[a,batch.result.value[i]]));const mint=fixture.evidence[1].params[0],source='741ZXYKzgjPZucRhPUQFK7kKAgP1ESJwimhumgGpuPHs',owner=base58(Buffer.from(raw.get(source).data[0],'base64').subarray(32,64));let calls=0;
 const market=JSON.parse(await readFile(join(repo,'fixtures/current/sta/reports/milestone4-validation/live-market.capture.json'),'utf8'),(_key,value,context)=>typeof value==='number'&&Number.isInteger(value)&&!Number.isSafeInteger(value)?JSON.rawJSON(context.source):value);let context=batch.result.context;
 for(const record of market.observations){if(record.method!=='getMultipleAccounts'||!record.result)continue;record.params[0].forEach((address,i)=>{const value=record.result.value[i];if(value==null)return;if(address==='SysvarC1ock11111111111111111111111111111111'&&record.result.context.slot>=context.slot){context=record.result.context;raw.set(address,value);}else if(!raw.has(address))raw.set(address,value);});}
 const walletSources=[source];
 for(const [byte,amount] of [[201,0n],[202,9007199254740993n]]){const address=base58(Buffer.alloc(32,byte)),account={...raw.get(source),data:[...raw.get(source).data]},data=Buffer.from(account.data[0],'base64');data.writeBigUInt64LE(amount,64);account.data[0]=data.toString('base64');raw.set(address,account);walletSources.push(address);}
 const server=createServer(async(req,res)=>{let bytes=0,body='';for await(const chunk of req){bytes+=chunk.length;if(bytes>65536){res.writeHead(413).end();return;}body+=chunk;}try{const{method,params}=JSON.parse(body);calls++;let result;if(method==='getGenesisHash')result='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d';else{let value;if(method==='getAccountInfo')value=raw.get(params[0])??null;else if(method==='getMultipleAccounts')value=params[0].map(a=>raw.get(a)??null);else if(method==='getTokenAccountsByOwner')value=walletSources.map(pubkey=>({pubkey,account:raw.get(pubkey)}));else if(method==='getTokenLargestAccounts')value=[{address:source,amount:'100',decimals:9,uiAmount:null}];else if(method==='getProgramAccounts'){value=[...raw].filter(([,v])=>v&&v.owner===params[0]&&(params[0]==='TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'||params[0]==='TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'?Buffer.from(v.data[0],'base64').length>=165&&base58(Buffer.from(v.data[0],'base64').subarray(0,32))===mint:v.space===904)).map(([pubkey,account])=>({pubkey,account}));}else throw new Error('unexpected method');result={context,value};}res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify({jsonrpc:'2.0',id:1,result}));}catch{res.writeHead(400).end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return{url:`http://127.0.0.1:${server.address().port}`,mint,source,owner,calls:()=>calls,stop:()=>new Promise(r=>server.close(r))};
}
