import { Header, Footer, workspaceHref } from './shell.js';

const REPO = 'https://github.com/thomasdevving/Eplyx';
export const CLI_COMMANDS = Object.freeze({
  compare: "eplyx compare --corpus retained/corpus.json \\\n  --current baseline.so --candidate candidate.so \\\n  --dependencies retained/dependencies --format json --out comparison.json",
  fixtureReproduce: "eplyx reproduce FIXTURE_OR_GROUP_ID \\\n  --current baseline.so --candidate candidate.so",
  bundle: "eplyx bundle build --corpus retained --baseline baseline.so \\\n  --dependencies retained/dependencies --out .eplyx/bundle\neplyx bundle verify --bundle .eplyx/bundle --format json",
  prepareHelp: "eplyx discover --help\neplyx historical acquire --help\neplyx versions resolve --help\neplyx versions upgrades --help\neplyx corpus select --help\neplyx bundle prepare --help",
  ci: "eplyx ci check --bundle .eplyx/bundle \\\n  --candidate target/deploy/program.so \\\n  --expectations .eplyx/expected-changes.toml \\\n  --format json --out eplyx-report.json",
  hostedCi: "./scripts/eplyx-submit.sh --api \"$EPLYX_API_URL\" \\\n  --project \"$EPLYX_PROJECT_ID\" --candidate target/deploy/program.so \\\n  --report-json eplyx-report.json --report-md eplyx-report.md",
  governance: "eplyx governance squads bind --multisig MULTISIG_ADDRESS \\\n  --transaction-index 1 --change-spec analysed.json \\\n  --out bound.json --evidence-out binding.json --format json\neplyx governance squads verify --change-spec bound.json --format json",
  attest: "eplyx governance squads attest --change-spec bound.json \\\n  --binding binding.json --artifacts evidence-store \\\n  --evidence-out attestation.json --format json",
  observe: "eplyx observe replay --input capture.json --format json\neplyx path capabilities --input capture.json --format json",
  parameter: 'eplyx parameter analyse \\\n  --change docs/examples/stake-pool-parameter-change.json \\\n  --bundle deploy/bundle \\\n  --record-id mainnet-spl-stake-pool-151010f709e113e7 \\\n  --out stake-fee-report.json\neplyx parameter reproduce \\\n  --change docs/examples/stake-pool-parameter-change.json \\\n  --report stake-fee-report.json',
  interaction: 'eplyx interaction analyse \\\n  --upgrade docs/examples/stake-pool-config-upgrade-change.json \\\n  --parameter docs/examples/stake-pool-parameter-change.json \\\n  --bundle deploy/bundle \\\n  --record-id mainnet-spl-stake-pool-151010f709e113e7 \\\n  --candidate artifacts/fixture_stake_pool_config_v2.so \\\n  --out ./code-fee-result --format json\neplyx interaction verify --artifact ./code-fee-result --format json\neplyx interaction reproduce --artifact ./code-fee-result --format json',
  parameterSearch: 'eplyx parameter search --change change.json --parent-report parameter-report.json \\\n  --spec search.json --out ./parameter-search --format json\neplyx parameter verify-search --artifact ./parameter-search --format json\neplyx parameter reproduce-search --artifact ./parameter-search --format json',
  parameterCases: 'eplyx parameter cases prepare --change change.json \\\n  --input retained-a.json retained-b.json --out selected-request\neplyx parameter cases analyse --manifest selected-request/manifest.json \\\n  --out selected-result\neplyx parameter cases verify --package selected-result\neplyx parameter cases reproduce --package selected-result',

  install: 'git clone --branch main https://github.com/thomasdevving/Eplyx.git\ncd Eplyx\ncargo build --locked --release -p eplyx-engine\nexport PATH="$PWD/target/release:$PATH"\neplyx --help',
  init: 'mkdir my-migration\ncd my-migration\neplyx init --migration --fixture',
  migration: 'eplyx doctor\neplyx migration analyse\neplyx runs --json\neplyx dashboard --no-open',
  search: 'eplyx migration search --run RUN_ID\neplyx migration gate --run RUN_ID --policy strict\neplyx migration reproduce COUNTEREXAMPLE_ID',
  upgrade: 'eplyx ci check --bundle .eplyx/bundle \\\n  --candidate target/deploy/program.so --format json',
  lifecycle: 'eplyx change lifecycle --scenario scenario.json --out change.json\neplyx lifecycle analyse --snapshot snapshot.json --scenario scenario.json \\\n  --change-spec change.json --at 2031-01-01T00:00:00Z \\\n  --format json --out report.json',
  paths: 'eplyx observe replay --help\neplyx path capabilities --help\neplyx path probe --help\neplyx path probe-withdrawal --help',
  sync: 'eplyx login --server "$EPLYX_URL"\neplyx link --project PROJECT_ID\neplyx sync --dry-run\neplyx sync --latest\neplyx logout',
});
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function CommandBlock(id, label, command) {
  return `<div class="command-block"><div class="command-bar"><span>${escape(label)}</span><button type="button" data-copy-command="command-${id}" aria-label="Copy ${escape(label)} commands">Copy</button></div><pre tabindex="0" aria-label="${escape(label)} commands"><code id="command-${id}">${escape(command)}</code></pre><span class="command-feedback" role="status" aria-live="polite"></span></div>`;
}

const guide = (path, label) => `<a href="${REPO}/blob/main/docs/${path}" class="text-link">${label} ↗</a>`;

export function CliPage() {
  return `<main id="main" class="inner-page cli-page">${Header({ light: true })}
    <section class="guide-intro"><p class="eyebrow"><span></span> Eplyx CLI</p><h1>From your terminal<br>to inspectable evidence.</h1><p>Run analyses locally, inspect saved results and reproduce findings. One <code>eplyx</code> binary covers upgrades, token migrations, lifecycle policies, two supported fee operations and current paths. Use the CLI for local inputs, repeatable checks and automation. <a href="/start" data-link class="text-link">Choose the right workflow ↗</a> · <a href="https://github.com/thomasdevving/Eplyx/blob/main/docs/README.md">Documentation index ↗</a></p><p data-technical>Local analytical records live in <code>.eplyx/</code>. Reproduction uses retained inputs; hosted sync transfers analytical documents without rerunning the engine. Required inputs and executable programs must be prepared separately.</p>
    <nav class="cli-task-index" aria-label="CLI guide sections"><a href="#install">Install the CLI</a><a href="#upgrades">Check a program upgrade</a><a href="#ci">Automate in CI</a><a href="#compare">Compare retained interactions</a><a href="#prepare">Prepare historical inputs</a><a href="#parameters">Compare a protocol fee</a><a href="#interaction">Compare code and fee</a><a href="#parameter-search">Local parameter extensions</a><a href="#governance">Check a Squads proposal</a><a href="#migration">Rehearse a migration</a><a href="#reproduce">Search a saved migration</a><a href="#lifecycle">Evaluate lifecycle terms</a><a href="#paths">Test a current path</a><a href="#sync">Share saved results</a></nav><p class="command-note">Examples use POSIX shell syntax. Replace file paths, IDs and dates with your own inputs. Start with a prepared workflow; command help alone does not acquire data or execute an analysis.</p></section>

    <section class="guide-section" id="install"><div><span class="guide-number">Install</span><h2>Build the CLI from source.</h2><p>The supported installation path here is a source build. A macOS Apple Silicon release-packaging workflow exists. Check <a href="https://github.com/thomasdevving/Eplyx/releases">GitHub Releases</a> for an actually published archive and its checksum; if none matches, use the source build. No one-line installer is provided.</p><p>Install Git, Rust stable with Cargo, and your platform’s native build tools first. Run these commands in the directory where you want the checkout.</p><p>The PATH command makes <code>eplyx</code> available in this terminal session. No account, wallet or provider is needed to build it or inspect command help.</p><a href="${REPO}" class="text-link">Browse the source ↗</a></div><div>${CommandBlock('install','Build from source',CLI_COMMANDS.install)}<p class="command-note">Check the build identity with <code>eplyx version --json</code>. A source build compiles the analysis engine; it does not build your candidate program. Keep the checkout to retain the CLI path.</p></div></section>

    <section class="guide-section" id="upgrades"><div><span class="guide-number">Program upgrades</span><h2>Check a build against a bundle.</h2><p class="guide-use"><strong>Use when:</strong> you have a proposed program build and a prepared bundle. <strong>You get:</strong> a scoped upgrade report and gate exit code.</p><p>Use a validated offline bundle containing the baseline, retained corpus and pinned dependencies. Build the candidate separately, then compare it against that bundle.</p><p>The gate reports expected, unexpected, exceeded, stale or unevaluable changes. Exit status belongs to the built binary, so invoke <code>eplyx</code> directly in CI.</p>${guide('phase-10-hosted-ci.md','Bundle preparation and CI guide')}<p><a href="/analyse" data-link class="text-link">Open the hosted upgrade form ↗</a></p></div><div>${CommandBlock('upgrade','Check a prepared upgrade bundle',CLI_COMMANDS.upgrade)}<p class="command-note">These paths must already contain your validated bundle and candidate. The command does not build code or acquire a corpus.</p></div></section>

    <section class="guide-section" id="ci"><div><span class="guide-number">Upgrade CI</span><h2>Check every candidate consistently.</h2><p class="guide-use"><strong>Use when:</strong> a team wants each pull request checked against an approved, pinned bundle.</p><p>Build the candidate in your own runner. For local CI, provision the Eplyx binary and bundle, then run the gate directly. A minimal expectation file contains <code>version = 1</code>; add only intentional changes and explicit bounds.</p><p>Keep declarations in version control. Read the report before interpreting the exit code: zero findings with no semantic coverage is not a clean result.</p>${guide('phase-10-hosted-ci.md','Gate semantics and expectation format')}<details><summary>Upgrade gate exit codes</summary><table class="cli-exit-codes"><thead><tr><th>Code</th><th>Meaning</th></tr></thead><tbody><tr><td>0</td><td>Passed within the evaluated coverage and declarations.</td></tr><tr><td>1</td><td>Unexpected, out-of-bounds or undeclarable changes.</td></tr><tr><td>2</td><td>Configuration, fidelity or evaluation error, including absent semantic coverage.</td></tr><tr><td>3</td><td>A declaration is stale.</td></tr><tr><td>4</td><td>Bundle or baseline incompatibility.</td></tr><tr><td>5</td><td>The corpus cannot evaluate a declaration.</td></tr></tbody></table></details></div><div>${CommandBlock('ci','Run a local upgrade gate',CLI_COMMANDS.ci)}<details><summary>Use an existing hosted project instead</summary><p>Run the repository’s submission client with Bash, curl, Python 3 and a SHA-256 utility. Supply <code>EPLYX_API_URL</code>, an accessible <code>EPLYX_PROJECT_ID</code> and a project-scoped <code>EPLYX_TOKEN</code> from CI configuration. The project must already have an active bundle.</p>${CommandBlock('hosted-ci','Submit a hosted upgrade check',CLI_COMMANDS.hostedCi)}<p class="command-note">This uploads the candidate, waits for the run and downloads reports. Add <code>--expectations .eplyx/expected-changes.toml</code> when that file exists. Client exit 70 means submission, transport or identity verification failed; 75 means the worker produced no verdict. Never treat either as a candidate regression.</p><a href="${REPO}/blob/main/.github/workflows/eplyx.yml" class="text-link">Hosted workflow example ↗</a></details></div></section>

    <section class="guide-section" id="compare"><div><span class="guide-number">Engineering investigation</span><h2>Compare retained interactions.</h2><p class="guide-use"><strong>Use when:</strong> you want a detailed local comparison of two builds over an existing replay corpus, before packaging an upgrade gate.</p><p>Supply the corpus JSON, baseline, candidate and the exact dependency binaries its records pin. The result describes only interactions that meet the replay contract. Use <code>ci check</code> for expectation-based gating.</p>${guide('phase-4-replay.md','Replay inputs and boundaries')}<details><summary>Reproduce a synthetic fixture regression</summary><p>The original <code>reproduce</code> command accepts fixture or regression-group IDs from the fixture-lending analysis. It is not a universal replay command for arbitrary mainnet findings. Both builds must be compatible with that fixture.</p>${CommandBlock('fixture-reproduce','Reproduce a fixture regression',CLI_COMMANDS.fixtureReproduce)}</details></div><div>${CommandBlock('compare','Compare a retained replay corpus',CLI_COMMANDS.compare)}<p class="command-note">The paths are examples, not files created by installation. Without <code>--corpus</code>, compare uses the synthetic fixture flow; keep the explicit corpus for retained-state investigations.</p></div></section>

    <section class="guide-section" id="prepare"><div><span class="guide-number">Operator preparation</span><h2>Prepare evidence before the check.</h2><p class="guide-use"><strong>Use when:</strong> you maintain a project’s replay evidence. An ordinary CI run consumes the approved bundle; it does not rebuild it.</p><p>Discover activity, acquire supported historical state and program versions, validate records, then assemble the bundle. Discovery alone does not create replay-ready evidence. Archive availability and supported transaction shapes limit what can be qualified.</p><p>The help commands do not contact a provider. Actual acquisition requires explicitly configured RPC/archive access and writes retained evidence.</p>${guide('phase-9-production-corpus.md','Corpus preparation and coverage')}</div><div>${CommandBlock('prepare-help','Inspect acquisition and selection inputs',CLI_COMMANDS.prepareHelp)}${CommandBlock('bundle','Bundle an already validated corpus',CLI_COMMANDS.bundle)}<p class="command-note"><code>retained/</code> must already contain its manifest and validated records; the baseline and dependencies must match those records. Bundle verification checks the retained inputs, not a new candidate.</p></div></section>

    <section class="guide-section" id="parameters"><div><span class="guide-number">Protocol parameters</span><h2>Compare one supported fee change.</h2><p class="guide-use"><strong>Use when:</strong> you want measured effects for an active Token-2022 transfer-fee rate or a retained Stake Pool SOL deposit fee.</p><p>The Stake Pool example uses the tracked bundle and declaration from the repository root. It simulates SetFee with an assumed manager signer, then compares the same DepositSol independently under both configurations. The example does not change on-chain state.</p><p>For Token-2022, provide <code>--capture transfer.capture.json</code> or <code>--input input.json</code> instead of a bundle. It derives only the already-active newer fee-bps field; it does not execute SetTransferFee. All expectations must match retained evidence.</p>${guide('parameter-analysis-guide.md','Fee-analysis walkthrough')}<p>${guide('protocol-parameter-change.md','Exact operations and hosted contract')}</p></div><div>${CommandBlock('parameter','Run the retained Stake Pool fee example',CLI_COMMANDS.parameter)}<p class="command-note">The output file must be new. These commands emit JSON without a format flag. Inspect the report status: command completion does not mean a fee is safe or authorised. Reproduction needs a compatible build and the retained report.</p></div></section>

    <section class="guide-section" id="interaction"><div><span class="guide-number">Code and fee</span><h2>Separate code, fee and combined effects.</h2><p class="guide-use"><strong>Use when:</strong> one retained Stake Pool deposit and an explicitly qualified candidate can support the bounded interaction experiment.</p><p>Build the separate config-capable test fixture using <code>./scripts/build-stake-pool-config-candidate.sh</code> first. This is constructed test code. The ordinary DepositSol-only regression fixture cannot substitute for it.</p><p>The engine compares baseline/proposed fees under both code versions, with independent configuration executions and a fixed Clock. A zero interaction can coexist with a fee effect. It does not simulate an actual loader upgrade or rollout order.</p>${guide('upgrade-parameter-interaction.md','Candidate requirements, results and hosted flow')}</div><div>${CommandBlock('interaction','Analyse and reproduce code-and-fee effects',CLI_COMMANDS.interaction)}<p class="command-note">Run from the repository root after building the exact admitted fixture. The output directory must be new. A retained hosted upgrade run can offer <strong>Compare code and fee</strong> when the server verifies eligibility.</p></div></section>

    <section class="guide-section" id="parameter-search"><div><span class="guide-number">Local parameter tools</span><h2>Search amounts or select retained cases.</h2><p>The source now includes bounded Token-2022 amount search and two- or three-case analysis from the verified <code>codex/analysis-integration</code> work. Build the current source and check <code>eplyx parameter --help</code>; older binaries may lack these commands. They are local CLI tools, with no hosted form. The fixed Step 11A review deployment does not gain them from a source update.</p><p>Search varies only the hypothetical transfer amount under one fixed proposal and unchanged account evidence. Its result reports tested and untested amounts; the smallest tested match is not a global minimum.</p><p>Case sets use two or three distinct observed source accounts and one exact proposal. Each pair runs independently with its own unchanged inputs. They do not represent a population or a shared account world.</p>${guide('parameter-analysis-guide.md','Required build, files and search schema')}</div><div><details><summary>Amount search with a compatible current build</summary><p>Requires a verified successful Token-2022 parent report, the same change and a search specification. Add <code>--capture transfer.capture.json</code> if the parent is bound to its original capture. These files are not supplied by CLI installation.</p>${CommandBlock('parameter-search','Search and reproduce retained transfer amounts',CLI_COMMANDS.parameterSearch)}</details><details><summary>Selected cases with a compatible current build</summary><p>Requires complete typed retained transfer inputs with distinct observed source accounts, compatible execution contracts and matching proposal expectations. Prepare the manifest with the same build used for fresh analysis.</p>${CommandBlock('parameter-cases','Analyse independent retained cases',CLI_COMMANDS.parameterCases)}</details><p class="command-note">These local extensions add no hosted form, automatic acquisition or coverage guarantee. Verification reads retained evidence; reproduction executes the saved experiment again.</p></div></section>

    <section class="guide-section" id="governance"><div><span class="guide-number">Squads V4 · Read-only</span><h2>Match a proposal to the analysed build.</h2><p class="guide-use"><strong>Use when:</strong> you are reviewing the supported single loader-v3 upgrade proposal. <strong>You get:</strong> dated binding evidence, separate from the economic analysis.</p><p>Start with an analysed upgrade ChangeSpec and explicitly configured <code>SOLANA_RPC_URL</code>. Replace the multisig and transaction index (shown as <code>1</code>) with the exact proposal. These commands read chain state; they do not sign or execute.</p><p>Bind first. Only a matched binding writes <code>bound.json</code>; then re-read it with verify. Use <code>eplyx governance squads acquire --help</code> if you need to derive the candidate and unbound ChangeSpec from a proposal first.</p>${guide('phase-g1-squads-governance-binding.md','Binding inputs and limits')}<p>${guide('phase-g2-squads-deployment-attestation.md','Deployment attestation requirements')}</p></div><div>${CommandBlock('governance','Bind and re-check a prepared proposal',CLI_COMMANDS.governance)}<details><summary>Attest deployment after execution</summary><p>Requires a sealed pre-execution matched binding and the exact candidate in the content-addressed store. An Executed proposal status alone is insufficient. Run this separately after execution; missing evidence can yield Unverifiable.</p>${CommandBlock('attest','Attest a previously bound deployment',CLI_COMMANDS.attest)}</details></div></section>

    <section class="guide-section" id="migration"><div><span class="guide-number">Token migration</span><h2>Prepare a proposal and state.</h2><p class="guide-use"><strong>Use when:</strong> you have a migration mechanism to rehearse. <strong>You get:</strong> a saved run with holder coverage, reconciliation and gate findings.</p><p>Create editable templates in a new directory. With <code>--fixture</code>, the project uses synthetic state instead of acquiring current chain state.</p><p><strong>Before analysing:</strong> fill in <code>migration.json</code>, configure the fixture and place your SBF candidate at the path in <code>eplyx.toml</code>. <code>init</code> alone does not create a complete runnable migration.</p><p>Building the reference candidate requires the pinned Solana SBF toolchain. The minimal example uses LiteSVM-bundled token programs. Archived workflows that pin captured programs additionally need their exact imported capture; a fresh clone does not include those private captures.</p>${guide('token-migration.md','Migration setup and fixture requirements')}</div><div>${CommandBlock('init','Create migration templates',CLI_COMMANDS.init)}${CommandBlock('migration','Analyse a prepared fixture project',CLI_COMMANDS.migration)}<p class="command-note">Doctor checks local configuration and inputs. The dashboard shows saved records on loopback; opening it does not start an analysis.</p></div></section>

    <section class="guide-section" id="reproduce"><div><span class="guide-number">Saved migration findings</span><h2>Keep the finding reproducible.</h2><p class="guide-use"><strong>Use when:</strong> a migration analysis has completed. These commands search and replay that migration’s saved inputs.</p><p>Search a saved migration, evaluate its gate and replay a counterexample offline. Use the IDs printed by your own run and search.</p><p>A strict gate can fail because required evidence is incomplete. A successful command does not establish issuer authorisation or signing possession.</p>${guide('dashboard.md','Local dashboard guide')}</div><div>${CommandBlock('search','Search and replay saved evidence',CLI_COMMANDS.search)}<p class="command-note"><code>RUN_ID</code> and <code>COUNTEREXAMPLE_ID</code> are placeholders. Reproduction needs a counterexample that your search actually saved.</p></div></section>

    <section class="guide-section" id="lifecycle"><div><span class="guide-number">Lifecycle policy</span><h2>Evaluate declared terms.</h2><p class="guide-use"><strong>Use when:</strong> you want to compare the effects of declared terms at specific times. <strong>You get:</strong> policy consequences, not a claim that a migration executed.</p><p>Supply a retained snapshot and scenario, create the lifecycle ChangeSpec and choose an evaluation time. Both commands below use your own input files.</p><p>The date is an example. Policy time does not change the recorded account state. A proposed successor or deadline is not proof of an official transition.</p>${guide('lifecycle.md','Lifecycle inputs and assurance')}</div><div>${CommandBlock('lifecycle','Evaluate a lifecycle scenario',CLI_COMMANDS.lifecycle)}<p class="command-note">Output files must be new. Saved evidence is never overwritten. Use <code>--help</code> for comparison times and recording results in a local project.</p></div></section>

    <section class="guide-section" id="paths"><div><span class="guide-number">Current paths</span><h2>Test one exact path.</h2><p class="guide-use"><strong>Use when:</strong> you have recorded observations or want to inspect the inputs required for a probe. Re-decoding and capability discovery do not prove execution.</p><p>Replay retained observations and inspect bounded Transfer, Meteora market-exit and liquidity-withdrawal checks. Each command’s help specifies the required captures and inputs.</p><p>Observation acquisition is a separate read-only operation. Offline execution requires recorded state and code; a balance or owner address alone cannot prove an exit or possession of a key.</p>${guide('current-state-analysis.md','Current-state guide')}</div><div>${CommandBlock('observe','Inspect a retained observation',CLI_COMMANDS.observe)}${CommandBlock('paths','Inspect current-path commands',CLI_COMMANDS.paths)}<p class="command-note">The first block reads your saved capture; the second displays probe help only. To execute a path, prepare the exact inputs described in that help and the current-state guide. Current-state acquisition has been verified with frozen fixtures and mock providers; successful fresh live-provider qualification remains a separate milestone.</p></div></section>

    <section class="guide-section" id="sync"><div><span class="guide-number">Optional hosted workspace</span><h2>Share retained analytical results.</h2><p class="guide-use"><strong>Use when:</strong> a local migration, lifecycle or current-state run is ready to share. Upgrade CI uses the separate submission flow above.</p><p>Use a service with workspace identity configured. Set <code>EPLYX_URL</code> to that service’s origin, approve the device code in your browser and replace <code>PROJECT_ID</code> with a project you can access.</p><p>Sync transfers exact analytical documents after a privacy check. It does not upload source, executable programs or captures, and it does not rerun the analysis.</p>${guide('cloud.md','Workspace setup and sync')}<p><a href="${workspaceHref()}" class="text-link">Open workspace ↗</a></p></div><div>${CommandBlock('sync','Link and sync a prepared local project',CLI_COMMANDS.sync)}<p class="command-note">Run inside a local project with saved results. Offline analysis does not require a hosted account. Availability depends on the service’s configuration.</p></div></section>
  </main>${Footer()}`;
}

export function attachCommandCopy() {
  document.querySelectorAll('[data-copy-command]').forEach(button => {
    button.addEventListener('click', async () => {
      const code = document.getElementById(button.dataset.copyCommand);
      const feedback = button.closest('.command-block').querySelector('.command-feedback');
      const block = button.closest('.command-block');
      try {
        await navigator.clipboard.writeText(code.textContent);
        feedback.textContent = 'Commands copied.';
        block.dataset.copyState = 'copied';
      } catch {
        const selection = window.getSelection();
        const range = document.createRange();
        range.selectNodeContents(code);
        selection.removeAllRanges();
        selection.addRange(range);
        code.parentElement.focus();
        feedback.textContent = 'Copy unavailable. Commands selected; use your keyboard to copy.';
        block.dataset.copyState = 'selected';
      }
    });
  });
}
