import { Header, Footer } from './shell.js';

export function TokenTransitionsSection() {
  return `<section class="section section--ink" id="token-transitions"><div class="section-heading section-heading--light reveal"><p class="eyebrow"><span></span> Token transitions</p><h2>Follow the change.<br>Account for every holder.</h2><p>A lifecycle event can change what a token represents. A proposed migration can change balances, authority and access. Inspect the declared terms, rehearse the mechanism and keep each conclusion tied to its evidence.</p><a href="/token-transitions" data-link class="text-link">Explore token transitions <span>↗</span></a></div></section>`;
}

export function TokenTransitionsPage() {
  return `<main id="main" class="inner-page transitions-page">${Header({light:true})}<section class="analyse-shell"><div class="analyse-copy"><p class="eyebrow"><span></span> Token transitions</p><h1>Know what a transition changes.</h1><p>Tokenised stocks and other token assets can change their terms, move to a replacement mint or lose a supported path. Eplyx separates the declared change from observed state and tested execution.</p><div class="input-model"><span>Observed state</span><b>+</b><span>Declared change</span><i>→</i><strong>Consequences in scope</strong></div></div><div class="transition-capabilities"><article><h2>Rehearse a token migration.</h2><p>Inspect holder coverage, funding, source and destination accounting, authority requirements and concrete counterexamples. A rehearsal runs in a local VM and applies only to its recorded inputs.</p></article><article><h2>Evaluate a lifecycle event.</h2><p>Compare declared policy times over one immutable snapshot. Keep entity consequences and protocol observations separate, with execution marked Not evaluated until there is execution evidence.</p></article><article><h2>Check an exact current path.</h2><p>Inspect a selected mint and owner, then evaluate bounded Transfer, market-exit or liquidity-withdrawal capabilities. Each path keeps its own evidence; public ownership does not establish possession of a signing key.</p></article><p class="form-note">An operator’s proposal is Declared only. It does not establish an issuer’s authorisation, redemption terms or eligibility.</p></div></section></main>${Footer()}`;
}
