// Hosted current-state workflow. Inputs are terms; all analytical status comes
// from the engine through the service. Each refresh is a new observation.
import { proposalHTML, attachProposals } from './proposal.js';
import { BASE, PROJECT } from './env.js';
import { esc, panel, pill, kv, ident, when, empty, words } from './ui.js';
import { fetchProjectCapabilities, capabilityFor, canSubmitCapability, capabilityHTML, capabilityFailureHTML, projectCapabilitiesHTML } from '/assets/capabilities.js';
const rootURL=()=>`/v1/projects/${encodeURIComponent(PROJECT)}/observations`;
async function call(path,body){let retryKey;if(body?.request_key){const terms={...body};delete terms.request_key;const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(path+JSON.stringify(terms)));retryKey='eplyx-pending-'+Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');const saved=sessionStorage.getItem(retryKey);if(saved)body.request_key=saved;else sessionStorage.setItem(retryKey,body.request_key);}const r=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const v=await r.json().catch(()=>({}));if(!r.ok)throw new Error(v.error||`Request failed (${r.status})`);if(retryKey)sessionStorage.removeItem(retryKey);return v;}
function field(label,name,type='text',value='',extra=''){return `<label class="analysis-field"><span>${esc(label)}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function shown(value){return value==null?'Not established':String(value);}
function observationHTML(record,result,capabilities){const wallet=result.wallet_observation,inspection=result.inspection??{},accounts=wallet?.token_accounts??[],pathCapability=capabilityFor(capabilities,'current_path'),pathReady=canSubmitCapability(pathCapability);
 return `${panel({title:'Current state',body:`${kv([['Mint',ident(result.asset?.mint,'addr')],['Source identity',esc(result.selection?.reference?'Saved first-party assertion; checked independently against observed state':'Custom token address; issuer identity unconfirmed')],['Identity comparison',esc((result.identity_mismatches??[]).length?'Source and observed identity differ; review the details':'No mismatch reported within the available observations')],['Decode and inspection',esc(words(inspection.status??'Unavailable'))],['Account sample',esc(words(result.discovery?.status??'Unavailable'))],['Observed metadata',esc(result.onchain_metadata?`${result.onchain_metadata.name??''} (${result.onchain_metadata.symbol??''})`:'Not available')],['Acquired',esc(when(result.acquisition?.completed_at))],['Public owner',ident(record.selection?.public_owner,'addr')]])}<p>${esc(result.identity_provenance??'Issuer association is unconfirmed.')}</p>${(result.identity_mismatches??[]).map(message=>`<p role="alert">${esc(message)}</p>`).join('')}<p>No official transition, issuer eligibility or signing possession is established by this observation.</p>${accounts.length?`<h3>Owner and selected mint</h3><p>Choose a token account for an exact check. These are public observations, not proof of wallet control.</p><label class="analysis-field"><span>Focused account</span><select data-focus>${accounts.map(a=>`<option value="${esc(a.address)}">${esc(a.address)} · ${esc(shown(a.state?.raw_balance))} raw</option>`).join('')}</select></label>`:empty(wallet?'No eligible account was observed for this owner and mint.':'Token scope does not inspect an owner’s wallet.')}`})}
 ${panel({title:'Five independent paths',body:`<div class="table-wrap"><table class="table"><thead><tr><th>Path</th><th>Observed status</th><th>Scope</th></tr></thead><tbody>${(result.paths??[]).map(p=>`<tr><td>${esc(words(p.path))}</td><td>${pill(p.status)}</td><td>${esc(p.status==='NotTested'?'No execution was requested for this observation.':p.reason??'No execution was requested.')}</td></tr>`).join('')}</tbody></table></div><p>Refresh starts every path untested. A Transfer result cannot establish market exit, withdrawal, redemption or official transition.</p>`})}
 ${accounts.length?panel({title:'Check one path',body:`${capabilityHTML(pathCapability,{compact:true})}<p data-path-availability role="status"></p><form data-path-form class="analysis-form"><label class="analysis-field"><span>Path to check</span><select name="path"><option value="Transfer">Transfer</option><option value="SecondaryMarketExit">Meteora market exit</option></select></label><label class="analysis-field"><span>Amount</span><select name="amount_mode" aria-label="Amount"><option value="Full">Full balance</option><option value="Custom">Custom amount</option></select></label>${field('Custom amount','amount_decimal','text','','inputmode="decimal" maxlength="280" disabled')}
 <div data-transfer-fields>${field('Recipient token account','recipient','text','','maxlength="44"')}</div><div data-market-fields hidden>${field('Paired output mint','output_mint','text','','maxlength="44"')}${field('Minimum output','minimum_output_decimal','text','','inputmode="decimal" maxlength="280"')}</div>
 <p>Only this source, mint, amount and destination are checked. A signature is assumed inside the local VM; no transaction is submitted and no funds move.</p><button class="button button--primary" type="submit"${pathReady?'':' disabled'}>Run offline path check</button></form><div data-path-result aria-live="polite"></div>`}):''}
 ${accounts.length?proposalHTML(capabilities):''}
 <div class="tech-only">${panel({title:'Observation identity',body:kv([['Observation',ident(record.id)],['Capture SHA-256',ident(record.capture?.sha256)]])})}</div>`;
}
async function waitForRun(id,node){for(let n=0;n<600;n++){if(!node.isConnected)return null;const record=await call(`/v1/runs/${encodeURIComponent(id)}`);if(['passed','failed','completed','execution_error'].includes(record.status))return record;await new Promise(r=>setTimeout(r,1000));}throw new Error('The run remains queued or running. Open Runs to follow it.');}
export async function analysisPage({query}){
 const capabilityRequest=fetchProjectCapabilities(PROJECT,call).then(capabilities=>({capabilities})).catch(error=>({error}));
 const catalogue=await call('/v1/catalogue');const entries=catalogue.entries??[],capabilityResult=await capabilityRequest,capabilities=capabilityResult.capabilities,observationCapability=capabilityFor(capabilities,'current_observation'),observationReady=canSubmitCapability(observationCapability);
 return {title:'Analyse current state',html:`<div class="page-head"><h1>Analyse current state.</h1><p>Observe one mint, or one public owner and mint. Request a separate offline check when you need execution evidence.</p></div>
 ${panel({title:'Choose an analysis',body:`<div class="analysis-choices"><article><h3>Current state</h3><p>Observe a mint or public owner, then request bounded checks over that observation.</p><a href="#current-state">Continue below</a></article><article><h3>Token migration</h3><p>Enter and preview one prepared Token Migration V1 proposal, then submit it through the hosted rehearsal path.</p>${capabilityHTML(capabilityFor(capabilities,'token_migration'),{compact:true})}<a class="button button--ghost" href="${BASE}/analyse/migration" data-link>${canSubmitCapability(capabilityFor(capabilities,'token_migration'))?'Prepare migration':'View requirements'}</a></article><article><h3>Lifecycle change</h3><p>Declare and preview one prepared lifecycle policy transition over an immutable snapshot.</p>${capabilityHTML(capabilityFor(capabilities,'lifecycle_change'),{compact:true})}<a class="button button--ghost" href="${BASE}/analyse/lifecycle" data-link>${canSubmitCapability(capabilityFor(capabilities,'lifecycle_change'))?'Prepare lifecycle change':'View requirements'}</a></article></div>`})}
 ${panel({title:'Analysis availability',body:capabilities?projectCapabilitiesHTML(capabilities):`${capabilityFailureHTML()}<button type="button" class="button button--ghost" data-capabilities-retry>Retry</button>`})}
 <div id="current-state">${panel({title:'Choose the current-state scope',body:`${capabilityHTML(observationCapability,{compact:true})}<form data-observe-form class="analysis-form">${field('Search catalogue','catalogue_filter','search','','autocomplete="off"')}<label class="analysis-field"><span>Asset</span><select name="catalogue"><option value="">Custom token address</option>${entries.map(e=>`<option value="${esc(e.mint)}">${esc(e.assertions[0]?.name)} (${esc(e.assertions[0]?.symbol)})</option>`).join('')}</select></label><p class="muted">${entries.length?`Saved PreStocks source, retrieved ${esc(when(catalogue.retrieved_at))}. Names are source assertions, not issuer verification.`:'No saved catalogue is available. Enter a canonical Solana mint address.'}</p>${field('Mint address','mint','text','','required maxlength="44" autocomplete="off"')}
 <label class="analysis-field"><span>Inspection scope</span><select name="scope"><option value="token">Token</option><option value="wallet">Public owner and mint</option></select></label><div data-owner hidden>${field('Public owner address','public_owner','text','','maxlength="44" autocomplete="off"')}</div><label data-sample><input name="sample_accounts" type="checkbox"> Include a bounded sample of token accounts</label><p>No wallet connection or private key is needed. Source identity, decoded state and execution are shown separately.</p><button type="submit" class="button button--primary"${observationReady?'':' disabled'}>Observe current state</button></form><p data-analysis-status role="status" aria-live="polite"></p>`})}
 </div><section data-observation></section>`,attach(node){
 const form=node.querySelector('[data-observe-form]'),status=node.querySelector('[data-analysis-status]'),output=node.querySelector('[data-observation]');let observation;
 node.querySelector('[data-capabilities-retry]')?.addEventListener('click',()=>window.dashboardNavigate(location.pathname+location.search));
 const error=e=>{status.textContent=e.message;};
 let customDraft='';
 form.elements.catalogue.addEventListener('change',()=>{if(form.elements.catalogue.value){if(!form.elements.mint.dataset.catalogue)customDraft=form.elements.mint.value;form.elements.mint.value=form.elements.catalogue.value;form.elements.mint.dataset.catalogue='1';}else{form.elements.mint.value=customDraft;delete form.elements.mint.dataset.catalogue;}});form.elements.mint.addEventListener('input',()=>{customDraft=form.elements.mint.value;delete form.elements.mint.dataset.catalogue;if(form.elements.mint.value!==form.elements.catalogue.value)form.elements.catalogue.value='';});
 form.elements.catalogue_filter.addEventListener('input',()=>{const query=form.elements.catalogue_filter.value.toLowerCase(),selected=form.elements.catalogue.value;form.elements.catalogue.innerHTML=`<option value="">Custom token address</option>${entries.filter(e=>e.mint===selected||e.assertions.some(a=>`${a.name} ${a.symbol}`.toLowerCase().includes(query))).map(e=>`<option value="${esc(e.mint)}" ${e.mint===selected?'selected':''}>${esc(e.assertions[0]?.name)} (${esc(e.assertions[0]?.symbol)})</option>`).join('')}`;});
 form.elements.scope.addEventListener('change',()=>{const wallet=form.elements.scope.value==='wallet';node.querySelector('[data-owner]').hidden=!wallet;form.elements.public_owner.required=wallet;node.querySelector('[data-sample]').hidden=wallet;if(wallet)form.elements.sample_accounts.checked=false;});
 async function display(id){const data=await call(`${rootURL()}/${encodeURIComponent(id)}`);if(!node.isConnected)return;observation=data.observation;output.innerHTML=observationHTML(observation,data.result,capabilities);const pathForm=output.querySelector('[data-path-form]');if(!pathForm)return;
 attachProposals({output,id,rootURL,call,waitForRun,node,capabilities});
 let caps;
 const availability=()=>{if(!pathForm.isConnected)return;const check=caps?.accounts?.find(a=>a.source===output.querySelector('[data-focus]').value)?.checks?.find(c=>c.path===pathForm.elements.path.value);pathForm.querySelector('button').disabled=!canSubmitCapability(capabilityFor(capabilities,'current_path'))||!check?.available;output.querySelector('[data-path-availability]').textContent=!canSubmitCapability(capabilityFor(capabilities,'current_path'))?'This hosted workflow is not currently available for this project.':check?.reason??(check?'Available for an offline check. No execution has been requested.':'Checking execution availability…');};
 availability();call(`${rootURL()}/${encodeURIComponent(id)}/capabilities`).then(value=>{caps=value;availability();}).catch(error);
 output.querySelector('[data-focus]').addEventListener('change',()=>{output.querySelector('[data-path-result]').replaceChildren();availability();});
 pathForm.elements.path.addEventListener('change',availability);
 pathForm.elements.amount_mode.addEventListener('change',()=>{pathForm.elements.amount_decimal.disabled=pathForm.elements.amount_mode.value!=='Custom';});
 pathForm.elements.path.addEventListener('change',()=>{const transfer=pathForm.elements.path.value==='Transfer';output.querySelector('[data-transfer-fields]').hidden=!transfer;output.querySelector('[data-market-fields]').hidden=transfer;});
 pathForm.addEventListener('submit',async event=>{event.preventDefault();const button=pathForm.querySelector('button');button.disabled=true;const target=output.querySelector('[data-path-result]'),selectedFocus=output.querySelector('[data-focus]').value;try{const values=Object.fromEntries(new FormData(pathForm));const market=values.path==='SecondaryMarketExit';const request={path:values.path,source:output.querySelector('[data-focus]').value,amount_mode:values.amount_mode,amount_decimal:values.amount_mode==='Custom'?values.amount_decimal:null,recipient:market?'':values.recipient,...(market?{output_mint:values.output_mint,minimum_output_decimal:values.minimum_output_decimal}:{})};target.textContent='Acquiring a bounded final state, then queuing offline execution…';const accepted=await call(`${rootURL()}/${encodeURIComponent(id)}/path-checks`,{request_key:crypto.randomUUID(),request});if(output.querySelector('[data-focus]')?.value!==selectedFocus)return;target.innerHTML=`<p>Check queued. <a href="${BASE}/runs/${esc(accepted.run_id)}" data-link>Open run</a></p>`;const done=await waitForRun(accepted.run_id,node);if(!done||output.querySelector('[data-focus]')?.value!==selectedFocus)return;if(!done.report_available)throw new Error(done.detail||'Execution could not complete.');const report=await call(`/v1/runs/${encodeURIComponent(done.run_id)}/report.json`);output.dispatchEvent(new Event('eplyx-check-complete'));if(output.querySelector('[data-focus]')?.value!==selectedFocus)return;target.innerHTML=`<h3>Recorded result: ${pill(report.status)}</h3><p>${esc(report.reason??report.scope??'Only the selected path was evaluated.')}</p>${kv([['Local execution',report.execution_performed?'Performed':'Not performed'],['Funds moved',report.funds_moved?'Yes':'No'],['Signing possession','Cannot be judged']])}<a href="${BASE}/runs/${esc(done.run_id)}" data-link>View complete run</a>`;}catch(e){if(output.querySelector('[data-focus]')?.value===selectedFocus)target.textContent=e.message;}finally{availability();}});
 }
 form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');if(!observationReady){status.textContent='Eplyx could not confirm that current-state observation is available.';button.disabled=true;return;}button.disabled=true;try{const f=Object.fromEntries(new FormData(form));const wallet=f.scope==='wallet';output.replaceChildren();observation=undefined;history.replaceState({},'',`${BASE}/analyse`);status.textContent='Acquiring bounded read-only observations…';const saved=await call(rootURL(),{request_key:crypto.randomUUID(),selection:{cluster:'solana-mainnet',mint:f.mint,catalogue_version:f.catalogue?catalogue.version:null,sample_accounts:!wallet&&f.sample_accounts==='on',public_owner:wallet?f.public_owner:null}});const id=saved.observation.id;history.replaceState({},'',`${BASE}/analyse?observation=${encodeURIComponent(id)}`);await display(id);const accepted=await call(`${rootURL()}/${encodeURIComponent(id)}/analyse`,{request_key:crypto.randomUUID()});status.innerHTML=`Observation saved; offline analysis queued. <a href="${BASE}/runs/${esc(accepted.run_id)}" data-link>Open run</a>`;button.textContent='Refresh current observation';}catch(e){error(e);}finally{button.disabled=!observationReady;}});
 const id=query.get('observation');if(id)display(id).catch(error);
 }};
}
