// Proposed terms stay separate from captured state and from execution evidence.
import { BASE } from './env.js';
import { esc, panel, pill, kv, words } from './ui.js';
const input=(label,name,value='',extra='')=>`<label class="analysis-field"><span>${esc(label)}</span><input name="${name}" value="${esc(value)}" ${extra}></label>`;
export function proposalHTML(){return `${panel({title:'Check a candidate migration',body:`<form data-candidate-form class="analysis-form"><p>Supply terms for the registered Token Migration V1 candidate. The reserve is a proposed local overlay, not observed issuer funding.</p>${input('Replacement mint','replacement_mint','','required maxlength="44"')}<label class="analysis-field"><span>Candidate amount</span><select name="amount_mode"><option value="Full">Full observed balance</option><option value="Custom">Custom amount</option></select></label>${input('Candidate custom amount','amount_decimal','','disabled inputmode="decimal"')}${input('Raw ratio numerator','numerator','1','required inputmode="numeric"')}${input('Raw ratio denominator','denominator','1','required inputmode="numeric"')}<label class="analysis-field"><span>Rounding</span><select name="rounding"><option value="floor">Floor</option><option value="ceiling">Ceiling</option></select></label>${input('Source fee (basis points)','fee_bps','0','type="number" min="0" max="10000" required')}${input('Proposed reserve (raw)','reserve_raw','1000000','required inputmode="numeric"')}<p>Amounts and ratios use exact integers. A successful check covers this account, amount and candidate only. It does not establish an official transition.</p><button class="button button--primary">Run candidate check</button></form><div data-candidate-result aria-live="polite"></div>`})}
${panel({title:'Stress a bounded sample',body:`<form data-stress-form class="analysis-form"><p>Reuse a saved candidate’s terms. Acquire a bounded current population, freeze up to ten cases before outcomes, and check each against its exact coherent final state. Full final balances are used; a one-account custom amount does not become a population amount.</p><label class="analysis-field"><span>Candidate for stress</span><select name="candidate_run_id" required><option value="">Select a saved candidate</option></select></label><p>The population scan is bounded to 1,000 decoded accounts and 1,000 authority lookups. Partial enumeration stays explicit. Results do not establish population rollout readiness.</p><button class="button button--primary">Run bounded stress</button></form><div data-stress-result aria-live="polite"></div>`})}
${panel({title:'Propose a replacement scenario',body:`<form data-preflight-form class="analysis-form"><p>Apply hypothetical policy times to the same captured bytes. A successor mint is inspected independently; its issuer association and conversion terms remain unconfirmed.</p>${input('Scenario replacement mint (optional)','successor_mint','','maxlength="44"')}${input('Proposed effective time','effective_at','','type="datetime-local" required')}${input('Proposed deadline (optional)','deadline','','type="datetime-local"')}<p>After a supplied deadline, transition remains required. Deadline passage alone cannot establish a blocked outcome.</p><label class="analysis-field"><span>Assurance question</span><select name="assurance"><option value="Mobility">Mobility of tested amounts</option><option value="FullTransition">Full transition</option></select></label><fieldset data-path-selections><legend>Saved path checks for this account</legend></fieldset><label class="analysis-field"><span>Saved candidate plan (optional)</span><select name="conversion_check_id"><option value="">No candidate selected</option></select></label><button class="button button--primary">Evaluate proposed scenario</button></form><div data-preflight-result aria-live="polite"></div>`})}`;}
export function candidateResult(report){return `<h3>Candidate result: ${pill(report.status)}</h3>${kv([['Exact input (raw)',esc(report.amount_raw)],['Replacement mint',esc(report.replacement_mint)],['Local execution',report.execution_performed?'Performed':'Not performed'],['Reconciliation',report.execution?.reconciled?'Exact checks passed':'No reconciled success'],['Official transition',pill(report.official_transition)],['Signing possession','Cannot be judged']])}<p>${esc(report.reason??'This result applies only to the supplied candidate and captured account.')}</p>`;}
export function preflightResult(report){return `<h3>Scenario: ${esc(words(report.preparation_status))}</h3><p>Proposed policy, unchanged captured balances. Population readiness is not assessed.</p>${kv([['Replacement inspection',esc(words(report.successor_verification?.status))],['Issuer relationship','Unconfirmed'],['Candidate plan',pill(report.replacement_conversion?.status)]])}<div class="table-wrap"><table class="table"><thead><tr><th>Policy time</th><th>Mobility</th><th>Candidate plan</th><th>Full transition</th></tr></thead><tbody>${(report.views??[]).map(v=>`<tr><td>${esc(words(v.id))}</td>${['mobility','candidate_plan','full_transition'].map(g=>`<td>${v.readiness?pill(v.readiness[g]?.status):'Before event; not evaluated'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
export function attachProposals({output,id,rootURL,call,waitForRun,node}){
 const stress=output.querySelector('[data-stress-form]');const candidate=output.querySelector('[data-candidate-form]'),preflight=output.querySelector('[data-preflight-form]');if(!candidate)return;
 const focus=()=>output.querySelector('[data-focus]')?.value;
 candidate.elements.amount_mode.addEventListener('change',()=>{candidate.elements.amount_decimal.disabled=candidate.elements.amount_mode.value!=='Custom';});
 async function reload(){const result=await call(`${rootURL()}/${encodeURIComponent(id)}/checks`);if(!output.isConnected)return;const chosenCandidate=preflight.elements.conversion_check_id.value,chosenStress=stress.elements.candidate_run_id.value,chosenPaths=new Set(new FormData(preflight).getAll('check_ids'));const selected=focus(),checks=(result.checks??[]).filter(c=>c.source===selected);preflight.querySelector('[data-path-selections]').innerHTML=`<legend>Saved path checks for this account</legend>${checks.filter(c=>c.kind==='current_path').map(c=>`<label><input type="checkbox" name="check_ids" value="${esc(c.run_id)}" ${chosenPaths.has(c.run_id)?'checked':''}> ${esc(words(c.path))} · ${esc(words(c.status))} · ${esc(c.amount_raw)} raw</label>`).join('')||'<p>No path check has completed for this account.</p>'}`;stress.elements.candidate_run_id.innerHTML=`<option value="">Select a saved candidate</option>${checks.filter(c=>c.kind==='current_candidate').map(c=>`<option value="${esc(c.run_id)}">${esc(words(c.status))} · ${esc(c.replacement_mint)}</option>`).join('')}`;if([...stress.elements.candidate_run_id.options].some(o=>o.value===chosenStress))stress.elements.candidate_run_id.value=chosenStress;preflight.elements.conversion_check_id.innerHTML=`<option value="">No candidate selected</option>${checks.filter(c=>c.kind==='current_candidate').map(c=>`<option value="${esc(c.run_id)}">${esc(words(c.status))} · ${esc(c.amount_raw)} raw · ${esc(c.replacement_mint)}</option>`).join('')}`;if([...preflight.elements.conversion_check_id.options].some(o=>o.value===chosenCandidate))preflight.elements.conversion_check_id.value=chosenCandidate;}
 output.querySelector('[data-focus]').addEventListener('change',()=>{for(const selector of ['[data-candidate-result]','[data-preflight-result]','[data-stress-result]'])output.querySelector(selector).replaceChildren();reload().catch(()=>{});});output.addEventListener('eplyx-check-complete',()=>reload().catch(()=>{}));reload().catch(()=>{});
 for(const [form,endpoint,selector,render] of [[candidate,'candidate-checks','[data-candidate-result]',candidateResult],[preflight,'preflights','[data-preflight-result]',preflightResult],[stress,'stress-checks','[data-stress-result]',stressResult]]){
 form.addEventListener('submit',async event=>{event.preventDefault();const target=output.querySelector(selector),button=form.querySelector('button');button.disabled=true;const selectedFocus=focus();try{const f=Object.fromEntries(new FormData(form));let request;if(form===candidate){request={source:focus(),replacement_mint:f.replacement_mint,amount_mode:f.amount_mode,amount_decimal:f.amount_mode==='Custom'?f.amount_decimal:null,numerator:f.numerator,denominator:f.denominator,rounding:f.rounding,fee_bps:Number(f.fee_bps),reserve_raw:f.reserve_raw};}else if(form===stress){request={candidate_run_id:f.candidate_run_id};}else{const check_ids=new FormData(form).getAll('check_ids');if(check_ids.length>4)throw new Error('Select at most four path checks.');request={source:focus(),successor_mint:f.successor_mint||null,effective_at:new Date(f.effective_at).toISOString(),deadline:f.deadline?new Date(f.deadline).toISOString():null,post_deadline:f.deadline?'TransitionStillRequired':null,assurance:f.assurance,check_ids,conversion_check_id:f.conversion_check_id||null};}
 target.textContent='Preparing immutable inputs, then queuing offline evaluation…';const accepted=await call(`${rootURL()}/${encodeURIComponent(id)}/${endpoint}`,{request_key:crypto.randomUUID(),...(form===stress?request:{request})});if(focus()!==selectedFocus)return;target.innerHTML=`<p>Queued. <a href="${BASE}/runs/${esc(accepted.run_id)}" data-link>Open run</a></p>`;const done=await waitForRun(accepted.run_id,node);if(!done||focus()!==selectedFocus)return;if(!done.report_available)throw new Error(done.detail||'Evaluation could not complete.');const report=await call(`/v1/runs/${encodeURIComponent(done.run_id)}/report.json`);if(focus()!==selectedFocus)return;target.innerHTML=`${render(report)}<a href="${BASE}/runs/${esc(done.run_id)}" data-link>View complete run</a>`;await reload();}catch(error){if(focus()===selectedFocus)target.textContent=error.message;}finally{button.disabled=false;}});
 }
}

export function stressResult(report){const r=report.report??{},c=r.coverage??{};return `<h3>Bounded stress completed.</h3>${kv([['Frozen cases',esc(c.exact_accounts_selected??'Not recorded')],['Executed accounts',esc(c.exact_accounts_executed??'Not recorded')],['Proven accounts',esc(c.exact_accounts_proven??'Not recorded')],['Population rollout',pill(c.population_rollout_readiness)],['Official transition',pill(r.official_transition)]])}<p>Each account retains its own final-state result. No peer inherits evidence and outcomes are not summed into reserve capacity.</p>`;}
